<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\Results\**" />
    <Compile Remove="Application\RRE\**" />
    <Compile Remove="Application\Search\**" />
    <Compile Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Application\Results\**" />
    <EmbeddedResource Remove="Application\RRE\**" />
    <EmbeddedResource Remove="Application\Search\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <None Remove="Application\Results\**" />
    <None Remove="Application\RRE\**" />
    <None Remove="Application\Search\**" />
    <None Remove="Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bioreference.Contracts.Order" Version="10.0.8" />
    <PackageReference Include="Bioreference.HL7Parser" Version="1.0.15" />
    <PackageReference Include="Bioreference.Messaging.Abstractions" Version="1.5.1" />
    <PackageReference Include="Bioreference.Messaging.Kafka" Version="1.4.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Bioreference.ResultService.Common\Bioreference.ResultService.Common.csproj" />
    <ProjectReference Include="..\..\Common\Bioreference.Contracts.Result\Bioreference.Contracts.Result.csproj" />
    <ProjectReference Include="..\Bioreference.ResultService.Application.Model\Bioreference.ResultService.Application.Model.csproj" />
    <ProjectReference Include="..\Bioreference.ResultService.DI.Interface\Bioreference.ResultService.DI.Interface.csproj" />
  </ItemGroup>

</Project>
