<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bioreference.ScanningService.Domain</RootNamespace>
    <AssemblyName>Bioreference.ScanningService.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BioReference.Logging" Version="10.1.0" />
  </ItemGroup>

</Project>
