<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bioreference.ScanningService.Infrastructure</RootNamespace>
    <AssemblyName>Bioreference.ScanningService.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Scaffolded\**" />
    <EmbeddedResource Remove="Scaffolded\**" />
    <None Remove="Scaffolded\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BioReference.Logging" Version="10.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables"
      Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions"
      Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"
      Version="10.0.0" />
    <PackageReference Include="PDFtoImage" Version="5.2.1" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.148.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\..\Application\Bioreference.ScanningService.Application\Bioreference.ScanningService.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Migrations\" />
    <Folder Include="Persistence\Scripts\" />
  </ItemGroup>

</Project>