<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bioreference.HL7Parser" Version="1.0.15" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Bioreference.ResultService.DI.Interface\Bioreference.ResultService.DI.Interface.csproj" />
  </ItemGroup>

</Project>
