// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Bioreference.ScanningService.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bioreference.ScanningService.Infrastructure.Persistence.Configurations;

public partial class BatchStatusConfiguration : IEntityTypeConfiguration<BatchStatus>
{
    public void Configure(EntityTypeBuilder<BatchStatus> entity)
    {
        entity.HasKey(e => e.BatchStatusId);

        entity.ToTable("BatchStatus");

        entity.Property(e => e.BatchStatusId)
            .HasColumnName("BatchStatusID");

        entity.Property(e => e.Name)
            .IsRequired()
            .HasMaxLength(255)
            .IsUnicode(false);

        entity.Property(e => e.IsActive)
            .IsRequired();

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<BatchStatus> entity);
}
