// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using Bioreference.ScanningService.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Bioreference.ScanningService.Infrastructure.Persistence.Configurations;

public partial class DocumentPageConfiguration : IEntityTypeConfiguration<DocumentPage>
{
    public void Configure(EntityTypeBuilder<DocumentPage> entity)
    {
        entity.HasKey(e => e.DocumentPageId).HasName("PK_PageDocument");


        entity.ToTable("DocumentPage");


        entity.Property(e => e.DocumentPageId).ValueGeneratedOnAdd();

        entity.Property(e => e.CreatedBy)

            .IsRequired()

            .HasMaxLength(255)

            .IsUnicode(false);

        entity.Property(e => e.CreatedDate).HasColumnType("datetime");

        entity.Property(e => e.Name)

            .HasMaxLength(100)

            .IsUnicode(false);

        entity.Property(e => e.PageURL)

            .HasMaxLength(500)

            .IsUnicode(false);

        entity.Property(e => e.UpdatedBy)

            .IsRequired()

            .HasMaxLength(255)

            .IsUnicode(false);

        entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

        entity.Property(e => e.SequenceNo)
            .HasColumnName("SequenceNo");

        entity.HasOne(d => d.Document).WithMany(p => p.DocumentPages) 

            .HasForeignKey(d => d.DocumentId)

            .HasConstraintName("FK_PageDocument_Document");
    }

    partial void OnConfigurePartial(EntityTypeBuilder<DocumentPage> modelBuilder);
}
