<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="HL7\**" />
    <EmbeddedResource Remove="HL7\**" />
    <None Remove="HL7\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bioreference.Contracts.Order" Version="10.0.8" />
    <PackageReference Include="Bioreference.HL7Parser" Version="1.0.15" />
    <PackageReference Include="Bioreference.Messaging.Abstractions" Version="1.5.1" />
    <PackageReference Include="Bioreference.Messaging.Kafka" Version="1.4.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.14" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Bioreference.ResultService.Application\Bioreference.ResultService.Application.csproj" />
    <ProjectReference Include="..\..\Common\Bioreference.Contracts.Result\Bioreference.Contracts.Result.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Root connections files hierarchy -->
    <None Update="connections.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="connections.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>connections.json</DependentUpon>
    </None>
    <None Update="connections.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>connections.json</DependentUpon>
    </None>
    <None Update="connections.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>connections.json</DependentUpon>
    </None>
    <None Update="connections.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>connections.json</DependentUpon>
    </None>
    <None Update="connections.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>connections.json</DependentUpon>
    </None>

    <!-- Audit Consumer appsettings hierarchy -->
    <None Update="Consumers\Audit\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Audit\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Audit\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Audit\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Audit\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Audit\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- CreateManifest Consumer appsettings hierarchy -->
    <None Update="Consumers\CreateManifest\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\CreateManifest\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\CreateManifest\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\CreateManifest\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\CreateManifest\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\CreateManifest\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- GenecysOrder Consumer appsettings hierarchy -->
    <None Update="Consumers\GenecysOrder\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\GenecysOrder\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\GenecysOrder\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\GenecysOrder\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\GenecysOrder\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\GenecysOrder\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- OutboundCHM Consumer appsettings hierarchy -->
    <None Update="Consumers\OutboundCHM\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\OutboundCHM\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\OutboundCHM\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\OutboundCHM\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\OutboundCHM\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\OutboundCHM\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- ProcessOrder Consumer appsettings hierarchy -->
    <None Update="Consumers\ProcessOrder\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\ProcessOrder\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ProcessOrder\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ProcessOrder\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ProcessOrder\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ProcessOrder\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Reflex Consumer appsettings hierarchy -->
    <None Update="Consumers\Reflex\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Reflex\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Reflex\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Reflex\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Reflex\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Reflex\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- ReportAck Consumer appsettings hierarchy -->
    <None Update="Consumers\ReportAck\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\ReportAck\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportAck\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportAck\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportAck\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportAck\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- ReportOut Consumer appsettings hierarchy -->
    <None Update="Consumers\ReportOut\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\ReportOut\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOut\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOut\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOut\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOut\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- ReportOutNonCum Consumer appsettings hierarchy -->
    <None Update="Consumers\ReportOutNonCum\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\ReportOutNonCum\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOutNonCum\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOutNonCum\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOutNonCum\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ReportOutNonCum\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- ResultCompleted Consumer appsettings hierarchy -->
    <None Update="Consumers\ResultCompleted\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\ResultCompleted\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultCompleted\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultCompleted\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultCompleted\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultCompleted\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- ResultReporting Consumer appsettings hierarchy -->
    <None Update="Consumers\ResultReporting\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\ResultReporting\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultReporting\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultReporting\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultReporting\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\ResultReporting\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\ARUP Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\ARUP\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\ARUP\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\ARUP\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\ARUP\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\ARUP\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\ARUP\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\Drugscan Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\Drugscan\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\Drugscan\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Drugscan\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Drugscan\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Drugscan\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Drugscan\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\FCS Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\FCS\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\FCS\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FCS\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FCS\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FCS\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FCS\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FIB\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FIB\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\FIB\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FIB\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FIB\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\FIB\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\Instrument Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\Instrument\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\Instrument\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Instrument\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Instrument\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Instrument\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Instrument\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\Labcorp1 Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\Labcorp1\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\Labcorp1\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp1\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp1\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp1\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp1\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\Labcorp2 Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\Labcorp2\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\Labcorp2\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp2\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp2\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp2\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\Labcorp2\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\MAYO Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\MAYO\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\MAYO\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MAYO\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MAYO\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MAYO\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MAYO\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\MDTX Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\MDTX\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\MDTX\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MDTX\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MDTX\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MDTX\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\MDTX\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\NMS Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\NMS\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\NMS\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\NMS\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\NMS\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\NMS\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\NMS\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QDClifton\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QDClifton\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\QDClifton\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QDClifton\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QDClifton\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QDClifton\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\QST Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\QST\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\QST\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QST\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QST\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QST\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\QST\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\SPEC Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\SPEC\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\SPEC\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\SPEC\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\SPEC\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\SPEC\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\SPEC\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\VAL Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\VAL\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\VAL\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VAL\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VAL\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VAL\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VAL\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>

    <!-- Result\VCOR Consumer appsettings hierarchy -->
    <None Update="Consumers\Result\VCOR\appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Consumers\Result\VCOR\appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VCOR\appsettings.Load.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VCOR\appsettings.Production.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VCOR\appsettings.QA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <DependentUpon>appsettings.json</DependentUpon>
    </None>
    <None Update="Consumers\Result\VCOR\appsettings.Stage.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
