// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class ActivityLog
{
    public long ActivityLogId { get; set; }

    public int BatchId { get; set; }

    public string UserId { get; set; }

    public int? DocumentId { get; set; }

    public int DocumentsScanned { get; set; }

    public int PagesScanned { get; set; }

    public string LogLevel { get; set; }

    public int? QueueId { get; set; }

    public string Description { get; set; }

    public DateTime LoggedDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Batch Batch { get; set; }
}