// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class BarCodeFormatDocumentTypeKeyword
{
    public int BarCodeDocumentTypeId { get; set; }

    public int DocumentTypeId { get; set; }

    public int BarCodeFormatId { get; set; }

    public int KeywordId { get; set; }

    public decimal? TopB { get; set; }

    public decimal? LeftB { get; set; }

    public decimal? WidthB { get; set; }

    public decimal? HeightB { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual BarCodeFormat BarCodeFormat { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual Keyword Keyword { get; set; }
}