// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class BarCodeFormat
{
    public int BarCodeFormatId { get; set; }

    public string Name { get; set; }

    public int? Length { get; set; }

    public string SearchDirection { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public bool? IsDeleted { get; set; }
  

    public virtual ICollection<BarCodeFormatDocumentTypeKeyword> BarCodeFormatDocumentTypeKeywords { get; set; } = new List<BarCodeFormatDocumentTypeKeyword>();
}