// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class Batch
{
    public int BatchId { get; set; }

    public string BatchNumber { get; set; }

    public string Name { get; set; }

    public int? ScanQueueId { get; set; }

    public int ScannerId { get; set; }

    public int? ScanningFormatId { get; set; }

    public string ScanMode { get; set; }

    public int? BatchStatusId { get; set; }

    public int TotalDocuments { get; set; }

    public int TotalPages { get; set; }

    public DateTime? StartedDate { get; set; }

    public DateTime? CompletedDate { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ActivityLog> ActivityLogs { get; set; } = new List<ActivityLog>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ScanQueue ScanQueue { get; set; }

    public virtual ScanningFormat ScanningFormat { get; set; }

    public virtual BatchStatus BatchStatus { get; set; }
}