// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class BatchStatus
{
    public int BatchStatusId { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Batch> Batches { get; set; } = new List<Batch>();
}
