// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class DocumentType
{
    public int DocumentTypeId { get; set; }

    public int GroupId { get; set; }

    public string Code { get; set; }

    public string DisplayName { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }
    public string DocumentNameFormat { get; set; }

    public string DocumentNameShortFormat { get; set; }

    public virtual ICollection<BarCodeFormatDocumentTypeKeyword> BarCodeFormatDocumentTypeKeywords { get; set; } = new List<BarCodeFormatDocumentTypeKeyword>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<DocumentTypeKeyword> DocumentTypeKeywords { get; set; } = new List<DocumentTypeKeyword>();

    public virtual DocumentTypeGroup Group { get; set; }

    public virtual ICollection<ScanQueueDocumentType> ScanQueueDocumentTypes { get; set; } = new List<ScanQueueDocumentType>();
}