// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Bioreference.ScanningService.Domain.Entities;

[Table("DocumentPage")]
public partial class DocumentPage
{
    [Key]
    public long DocumentPageId { get; set; }
    public long? DocumentId { get; set; }
    public string Name { get; set; }
    public string PageURL { get; set; }
    public string CreatedBy { get; set; }
    public DateTime CreatedDate { get; set; }
    public string UpdatedBy { get; set; }
    public DateTime UpdatedDate { get; set; }
    public bool IsDeleted { get; set; }
    public int? SequenceNo { get; set; }
    public virtual Document Document { get; set; }
}
