// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class Document
{
    public long DocumentId { get; set; }

    public int? BatchId { get; set; }

    public int DocumentTypeId { get; set; }

    public string Name { get; set; }
    public string ShortName { get; set; }
    
    public string BarcodeValue { get; set; }

    public string IndexingValue { get; set; }

    public string DocUrl { get; set; }

    public DateTime? DocumentDate { get; set; }

    public string SpecimenNumber { get; set; }

    public DateTime DatePosted { get; set; }

    public string Status { get; set; }

    public bool IsIndexed { get; set; }

    public int TotalPages { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }
    public string ThumbnailUrl { get; set; }


    public virtual Batch Batch { get; set; }

    public virtual ICollection<DocumentKeywordValue> DocumentKeywordValues { get; set; } = new List<DocumentKeywordValue>();

    public virtual DocumentType DocumentType { get; set; }
    public virtual ICollection<DocumentPage> DocumentPages { get; set; } = new List<DocumentPage>();

}