// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class DocumentKeywordValue
{
    public int DocumentKeywordValueId { get; set; }

    public long DocumentId { get; set; }

    public int KeywordId { get; set; }

    public string AlphanumericValue { get; set; }

    public DateTime? DateTimeValue { get; set; }

    public decimal? DecimalValue { get; set; }

    public long? LongValue { get; set; }

    public string TextValue { get; set; }

    public int Sequence { get; set; }
    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public virtual Document Document { get; set; }

    public virtual Keyword Keyword { get; set; }
}