// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class DocumentTypeKeyword
{
    public int DocumentTypeKeywordId { get; set; }

    public int DocumentTypeId { get; set; }

    public int KeywordId { get; set; }

    public bool IsRequired { get; set; }

    public bool IsActive { get; set; }

    public int DisplayOrder { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual Keyword Keyword { get; set; }
}