// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class Keyword
{
    public int KeywordId { get; set; }

    public string Name { get; set; }

    public string DataType { get; set; }

    public string ControlType { get; set; }

    public bool IsRequired { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public int? OnBaseTableType { get; set; }

    public virtual ICollection<BarCodeFormatDocumentTypeKeyword> BarCodeFormatDocumentTypeKeywords { get; set; } = new List<BarCodeFormatDocumentTypeKeyword>();

    public virtual ICollection<DocumentKeywordValue> DocumentKeywordValues { get; set; } = new List<DocumentKeywordValue>();

    public virtual ICollection<DocumentTypeKeyword> DocumentTypeKeywords { get; set; } = new List<DocumentTypeKeyword>();
}