// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class ScanQueue
{
    public int ScanQueueId { get; set; }

    public string Name { get; set; }

    public bool IsAutoCommit { get; set; }

    public DateTime? LastUsedDate { get; set; }

    public bool IsActive { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime UpdatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Batch> Batches { get; set; } = new List<Batch>();

    public virtual ICollection<ScanQueueDocumentType> ScanQueueDocumentTypes { get; set; } = new List<ScanQueueDocumentType>();
}