// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bioreference.ScanningService.Domain.Entities;

public partial class ScanQueueDocumentType
{
    public int ScanQueueDocumentTypeId { get; set; }

    public int ScanQueueId { get; set; }

    public int DocumentTypeId { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual ScanQueue ScanQueue { get; set; }
}