using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Transactions;
using Bioreference.Data;
using Bioreference.Data.Audit;
using Bioreference.Data.Client;
using Microsoft.VisualBasic.CompilerServices;

namespace Bioreference.LIS
{

    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 
    // 
    [Serializable()]
    public class InstAnalyzer : AuditDataClassBase
    {


        #region  Private Members 

        private int m_analyzerid;
        private int m_instrumentgroupid;
        private string m_analyzername;
        private string m_model;
        private string m_vendor;
        private int m_divisionid;
        private string m_divisioncode;
        private bool m_isdeleted;
        private DateTime m_createddate;
        private string m_createdby;
        private DateTime m_updateddate;
        private string m_updatedby;

        private InstGroup m_parent;
        private InstAnalyticalUnits m_objInstAnalyticalUnits;

        #endregion

        #region  Public Properties 


        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property AnalyzerId
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public int AnalyzerId
        {
            get
            {
                return m_analyzerid;
            }
            set
            {
                m_analyzerid = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property InstrumentGroupId
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public int InstrumentGroupId
        {
            get
            {
                return m_instrumentgroupid;
            }
            set
            {
                m_instrumentgroupid = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property AnalyzerName
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string AnalyzerName
        {
            get
            {
                return m_analyzername;
            }
            set
            {
                m_analyzername = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property Model
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string Model
        {
            get
            {
                return m_model;
            }
            set
            {
                m_model = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property Vendor
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string Vendor
        {
            get
            {
                return m_vendor;
            }
            set
            {
                m_vendor = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property DivisionId
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public int DivisionId
        {
            get
            {
                return m_divisionid;
            }
            set
            {
                m_divisionid = value;
            }
        }

        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property AnalyzerName
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string DivisionCode
        {
            get
            {
                return m_divisioncode;
            }
            set
            {
                m_divisioncode = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property IsDeleted
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public bool IsDeleted
        {
            get
            {
                return m_isdeleted;
            }
            set
            {
                m_isdeleted = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property CreatedDate
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public DateTime CreatedDate
        {
            get
            {
                return m_createddate;
            }
            set
            {
                m_createddate = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property CreatedBy
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string CreatedBy
        {
            get
            {
                return m_createdby;
            }
            set
            {
                m_createdby = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property UpdatedDate
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public DateTime UpdatedDate
        {
            get
            {
                return m_updateddate;
            }
            set
            {
                m_updateddate = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property UpdatedBy
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string UpdatedBy
        {
            get
            {
                return m_updatedby;
            }
            set
            {
                m_updatedby = value;
            }
        }

        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property InstAnalyzerList
        // '''''''''''''''''''''''''''''''''''''''''''''
        public InstAnalyticalUnits InstAnalyticalUnitList
        {
            get
            {
                return m_objInstAnalyticalUnits;
            }
        }


        #endregion

        #region  Overridden Properties 

        public override object IdentifierId
        {
            get
            {
                return m_analyzerid;
            }
        }

        #endregion

        #region Constructor

        internal InstAnalyzer()
        {

            m_objInstAnalyticalUnits = new InstAnalyticalUnits(this);
            FlagDirty();
        }

        internal InstAnalyzer(int Inst_AnalyzerID)
        {
            m_analyzerid = Inst_AnalyzerID;
            m_objInstAnalyticalUnits = new InstAnalyticalUnits(this);
            FlagDirty();
        }

        internal InstAnalyzer(InstGroup parent)
        {
            m_parent = parent;
            m_analyzerid = 0;

            FlagDirty();
        }

        #endregion

        #region  Criteria Class 
        [Serializable()]
        internal class Criteria
        {
            private int m_Inst_AnalyzerID;

            public int Inst_AnalyzerID
            {
                get
                {
                    return m_Inst_AnalyzerID;
                }
            }

            public Criteria(int Inst_AnalyzerId)
            {
                m_Inst_AnalyzerID = Inst_AnalyzerId;
            }

        }

        #endregion

        #region Public Shared Methods
        public static InstAnalyzer CreateInst_Analyzer(int Inst_AnalyzerID)
        {
            var objInst_Analyzer = Fetch(Inst_AnalyzerID);

            if (objInst_Analyzer == null)
            {
                objInst_Analyzer = new InstAnalyzer(Inst_AnalyzerID);
            }

            return objInst_Analyzer;
        }

        public static InstAnalyzer Fetch(int Inst_AnalyzerID)
        {
            InstAnalyzer objInst_Analyzer = (InstAnalyzer)DataFactory.Fetch(new Criteria(Inst_AnalyzerID));
            if (objInst_Analyzer is null || objInst_Analyzer.AnalyzerId == 0)
            {
                return null;
            }
            else
            {
                return objInst_Analyzer;
            }
        }

        #endregion

        public InstAnalyticalUnit CreateAnalyticalUnit()
        {
            // create a Child, add it to the specimen list and return it
            var objInstAnalyticalUnit = new InstAnalyticalUnit(this);
            m_objInstAnalyticalUnits.List.Add(objInstAnalyticalUnit);
            return objInstAnalyticalUnit;
        }

        #region  Overridden Methods 

        protected override void DataFactory_Fetch(object criteria)
        {
            try
            {
                Criteria c = (Criteria)criteria;
                var @params = new List<DbParameter>();
                DataTable[] dt = null;
                var dw = new DataWrapper(Configuration.ConnectionString);

                @params.Add((DbParameter)dw.CreateParameter("@AnalyzerID", DbType.Int32, c.Inst_AnalyzerID));
                dt = dw.ExecuteProcedure("lis_InstAnalyzer_FetchByAnalyzerID", @params.ToArray());

                if (dt is not null && dt.Length > 0 && dt[0].Rows.Count > 0)
                {
                    Load(dt[0].Rows[0]);
                }
                FetchAnalyticalUnits(m_analyzerid);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public void Load(DataRow row)
        {
            try
            {
                m_analyzerid = Conversions.ToInteger(row["AnalyzerID"]);
                m_instrumentgroupid = Conversions.ToInteger(row["InstrumentGroupId"]);
                m_analyzername = Conversions.ToString(row["AnalyzerName"]);
                m_model = Conversions.ToString(row["Model"]);
                m_vendor = Conversions.ToString(row["Vendor"]);
                m_divisionid = Conversions.ToInteger(row["DivisionId"]);
                m_isdeleted = Conversions.ToBoolean(row["IsDeleted"]);

                m_createdby = Conversions.ToString(row["CreatedBy"]);
                m_createddate = Conversions.ToDate(row["CreatedDate"]);

                if (row["UpdatedDate"] is DBNull)
                {
                    m_updateddate = Conversions.ToDate(row["CreatedDate"]);
                }
                else
                {
                    m_updateddate = Conversions.ToDate(row["UpdatedDate"]);
                }

                if (row["UpdatedBy"] is DBNull)
                {
                    m_updatedby = Conversions.ToString(row["CreatedBy"]);
                }
                else
                {
                    m_updatedby = Conversions.ToString(row["UpdatedBy"]);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        private void FetchAnalyticalUnits(int Inst_AnalyzerID)
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();
            try
            {
                // When criteria become available, we need to change this routine to handle the different
                // searches            
                @params.Add((DbParameter)dw.CreateParameter("@AnalyzerID", DbType.Int32, Inst_AnalyzerID));

                DataTable[] dt = dw.ExecuteProcedure("lis_InstAnalyticalUnit_FetchByAnalyzerID", @params.ToArray());
                if (dt[0].Rows.Count > 0)
                {
                    m_objInstAnalyticalUnits.Load(dt);
                }
            }

            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void DataFactory_Save()
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();

            try
            {
                var options = new TransactionOptions();
                options.IsolationLevel = System.Transactions.IsolationLevel.ReadUncommitted;
                options.Timeout = new TimeSpan(0, 2, 0);

                using (var scope = new TransactionScope(TransactionScopeOption.Required, options))
                {
                    @params.Add((DbParameter)dw.CreateParameter("@AnalyzerID", DbType.Int32, AnalyzerId, ParameterDirection.InputOutput));
                    @params.Add((DbParameter)dw.CreateParameter("@InstrumentGroupId", DbType.Int32, InstrumentGroupId));
                    @params.Add((DbParameter)dw.CreateParameter("@AnalyzerName", DbType.String, AnalyzerName));
                    @params.Add((DbParameter)dw.CreateParameter("@Model", DbType.String, Model));
                    @params.Add((DbParameter)dw.CreateParameter("@Vendor", DbType.String, Vendor));
                    @params.Add((DbParameter)dw.CreateParameter("@DivisionId", DbType.Int32, DivisionId));

                    @params.Add((DbParameter)dw.CreateParameter("@IsDeleted", DbType.Boolean, IsDeleted));

                    @params.Add((DbParameter)dw.CreateParameter("@UpdatedBy", DbType.String, UpdatedBy));

                    m_analyzerid = Conversions.ToInteger(dw.ExecuteNonQuery("lis_InstAnalyzer_Save", @params.ToArray())["@AnalyzerID"].Value);

                    if (!IsDeleted)
                    {
                        foreach (InstAnalyticalUnit objAnalyticalUnit in m_objInstAnalyticalUnits.List)
                            objAnalyticalUnit.AnalyzerId = m_analyzerid;
                        m_objInstAnalyticalUnits.List.Update();
                    }
                    scope.Complete();

                }
            }

            catch (Exception ex)
            {
                throw ex;
            }

        }
        #endregion

    }
}