using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Bioreference.Data;
using Bioreference.Data.Client;

namespace Bioreference.LIS
{

    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 
    // 
    [Serializable()]
    public class InstAnalyzers : DataClassBase
    {

        #region  Private Members 

        private InstAnalyzerList m_list;
        private InstGroup m_parent;

        #endregion

        #region  Public Properties 

        public InstAnalyzerList List
        {
            get
            {
                return m_list;
            }
        }

        #endregion

        #region  Constructor 

        private InstAnalyzers()
        {
            m_list = new InstAnalyzerList();
        }

        internal InstAnalyzers(InstGroup parent)
        {
            m_parent = parent;
            m_list = new InstAnalyzerList();
        }
        #endregion

        #region  Criteria Class 
        [Serializable()]
        internal class Criteria
        {

            public Criteria(int instrumentGroupID)
            {
                m_intrumentGroupID = instrumentGroupID;
            }

            private int m_intrumentGroupID;
            public int InstrumentGroupID
            {
                get
                {
                    return m_intrumentGroupID;
                }
                set
                {
                    m_intrumentGroupID = value;
                }
            }



        }
        #endregion

        #region  Public Methods 
        // retrieves all Inst_Analyzers
        public static InstAnalyzers Fetch(int instrumentGroupID)
        {
            InstAnalyzers objInst_Analyzers = (InstAnalyzers)DataFactory.Fetch(new Criteria(instrumentGroupID));
            return objInst_Analyzers;
        }

        #endregion


        #region  Overridden Methods 

        protected override void DataFactory_Fetch(object criteria)
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();
            Criteria crit = (Criteria)criteria;
            try
            {
                @params.Add((DbParameter)dw.CreateParameter("@InstrumentGroupId", DbType.String, crit.InstrumentGroupID));
                DataTable[] dt = dw.ExecuteProcedure("lis_InstAnalyzer_FetchByGroupID", @params.ToArray());
                if (dt[0].Rows.Count > 0)
                {
                    Load(dt);
                }
            }

            catch (Exception ex)
            {
                throw ex;
            }
        }

        #endregion

        #region  Private Methods 

        internal void Load(DataTable[] dt)
        {
            InstAnalyzer objInst_Analyzer = null;
            {
                ref var withBlock = ref dt[0];
                foreach (DataRow dr in withBlock.Rows)
                {
                    objInst_Analyzer = new InstAnalyzer();
                    objInst_Analyzer.Load(dr);
                    m_list.Add(objInst_Analyzer);
                }
            }
        }

        #endregion

    }
}