using System;
using Bioreference.Data;

namespace Bioreference.LIS
{


    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 3:27:20 PM
    // 
    [Serializable()]
    public class InstAnalyticalUnitList : DataClassCollectionBase
    {

        internal InstAnalyticalUnitList()
        {
        }

        internal void Add(InstAnalyticalUnit InstAnalyticalUnit)
        {

            List.Add(InstAnalyticalUnit);

        }

        internal void Remove(InstAnalyticalUnit InstAnalyticalUnit)
        {

            List.Remove(InstAnalyticalUnit);

        }

        public InstAnalyticalUnit this[int index]
        {
            get
            {
                return (InstAnalyticalUnit)List[index];
            }
        }

        internal void Update()
        {

            foreach (InstAnalyticalUnit w in List)
                w.Save();

            // For Each w As InstAnalyticalUnit In MyBase.DeletedItemsList
            // w.Delete()
            // Next

        }

        public override bool IsDirty
        {
            get
            {
                if (!(DeletedItemsList == null) && DeletedItemsList.Count > 0)
                    return true;

                foreach (InstAnalyticalUnit w in List)
                {
                    if (w.IsDirty)
                        return true;
                }

                return false;
            }
        }
    }
}