using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Bioreference.Data;
using Bioreference.Data.Client;

namespace Bioreference.LIS
{


    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 
    // 
    [Serializable()]
    public class InstGroups : DataClassBase
    {

        #region  Private Members 

        private InstGroupList m_list;

        #endregion

        #region  Public Properties 

        public InstGroupList List
        {
            get
            {
                return m_list;
            }
        }

        #endregion

        #region  Constructor 

        private InstGroups()
        {
            m_list = new InstGroupList();
        }

        #endregion

        #region  Criteria Class 
        [Serializable()]
        internal class Criteria
        {

        }
        #endregion

        #region  Public Methods 
        // retrieves all Inst_InstrumentGroups
        public static InstGroups Fetch()
        {
            InstGroups objInstrumentGroups = (InstGroups)DataFactory.Fetch(new Criteria());
            return objInstrumentGroups;
        }

        #endregion


        #region  Overridden Methods 

        protected override void DataFactory_Fetch(object criteria)
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();
            Criteria crit = (Criteria)criteria;
            try
            {
                // params.Add(dw.CreateParameter("@ParamName", DbType.String, crit.Property))

                DataTable[] dt = dw.ExecuteProcedure("lis_InstGroup_Fetch", @params.ToArray());
                if (dt[0].Rows.Count > 0)
                {
                    Load(dt);
                }
            }

            catch (Exception ex)
            {
                throw ex;
            }
        }

        #endregion

        #region  Private Methods 

        private void Load(DataTable[] dt)
        {
            InstGroup objInst_InstrumentGroup = null;
            {
                ref var withBlock = ref dt[0];
                foreach (DataRow dr in withBlock.Rows)
                {
                    objInst_InstrumentGroup = new InstGroup();
                    objInst_InstrumentGroup.Load(dr);
                    m_list.Add(objInst_InstrumentGroup);
                }
            }
        }

        #endregion

    }
}