using System;
using Bioreference.Data;

namespace Bioreference.LIS
{

    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 
    // 
    [Serializable]
    public class InstAnalyzerList : DataClassCollectionBase
    {

        internal InstAnalyzerList()
        {
        }

        internal void Add(InstAnalyzer inst_analyzer)
        {

            List.Add(inst_analyzer);

        }

        internal void Remove(InstAnalyzer inst_analyzer)
        {

            List.Remove(inst_analyzer);

        }

        public InstAnalyzer this[int index]
        {
            get
            {
                return (InstAnalyzer)List[index];
            }
        }

        internal void Update()
        {

            foreach (InstAnalyzer w in List)
                w.Save();

            // For Each w As Inst_Analyzer In MyBase.DeletedItemsList
            // w.Delete()
            // Next

        }

        public override bool IsDirty
        {
            get
            {
                if (!(DeletedItemsList == null) && DeletedItemsList.Count > 0)
                    return true;

                foreach (InstAnalyzer w in List)
                {
                    if (w.IsDirty)
                        return true;
                }

                return false;
            }
        }
    }
}