using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Transactions;
using Bioreference.Data;
using Bioreference.Data.Audit;
using Bioreference.Data.Client;
using Microsoft.VisualBasic.CompilerServices;

namespace Bioreference.LIS
{

    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 3:27:20 PM
    // 
    [Serializable()]
    public class InstAnalyticalUnit : AuditDataClassBase
    {


        #region  Private Members 

        private int m_analyticalunitid;
        private int m_analyzerid;
        private string m_analyticalunitname;
        private string m_instrumentid;
        private string m_analyticalunitserial;
        private bool m_isdeleted;
        private DateTime m_createddate;
        private string m_createdby;
        private DateTime m_updateddate;
        private string m_updatedby;

        private InstAnalyzer m_parent;

        #endregion

        #region  Public Properties 


        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property AnalyticalUnitID
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public int AnalyticalUnitID
        {
            get
            {
                return m_analyticalunitid;
            }
            set
            {
                m_analyticalunitid = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property AnalyzerId
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public int AnalyzerId
        {
            get
            {
                return m_analyzerid;
            }
            set
            {
                m_analyzerid = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property AnalyticalUnitName
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string AnalyticalUnitName
        {
            get
            {
                return m_analyticalunitname;
            }
            set
            {
                m_analyticalunitname = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property InstrumentId
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string InstrumentId
        {
            get
            {
                return m_instrumentid;
            }
            set
            {
                m_instrumentid = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property AnalyticalUnitSerial
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string AnalyticalUnitSerial
        {
            get
            {
                return m_analyticalunitserial;
            }
            set
            {
                m_analyticalunitserial = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property IsDeleted
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public bool IsDeleted
        {
            get
            {
                return m_isdeleted;
            }
            set
            {
                m_isdeleted = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property CreatedDate
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public DateTime CreatedDate
        {
            get
            {
                return m_createddate;
            }
            set
            {
                m_createddate = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property CreatedBy
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string CreatedBy
        {
            get
            {
                return m_createdby;
            }
            set
            {
                m_createdby = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property UpdatedDate
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public DateTime UpdatedDate
        {
            get
            {
                return m_updateddate;
            }
            set
            {
                m_updateddate = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property UpdatedBy
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string UpdatedBy
        {
            get
            {
                return m_updatedby;
            }
            set
            {
                m_updatedby = value;
            }
        }






        #endregion

        #region  Overridden Properties 

        public override object IdentifierId
        {
            get
            {
                return m_analyticalunitid;
            }
        }

        #endregion

        #region Constructor

        internal InstAnalyticalUnit()
        {
            FlagDirty();
        }

        internal InstAnalyticalUnit(int InstAnalyticalUnitID)
        {
            m_analyticalunitid = InstAnalyticalUnitID;
            FlagDirty();
        }


        internal InstAnalyticalUnit(InstAnalyzer analyzer)
        {
            m_parent = analyzer;
            m_analyzerid = analyzer.AnalyzerId;
            m_analyticalunitid = 0;
        }

        #endregion

        #region  Criteria Class 
        [Serializable()]
        internal class Criteria
        {
            private int m_InstAnalyticalUnitID;
            private string m_instrumentID;

            public int InstAnalyticalUnitID
            {
                get
                {
                    return m_InstAnalyticalUnitID;
                }
            }

            public string InstrumentID
            {
                get
                {
                    return m_instrumentID;
                }
            }

            public Criteria(int InstAnalyticalUnitId)
            {
                m_InstAnalyticalUnitID = InstAnalyticalUnitId;
                m_instrumentID = "";
            }

            public Criteria(int InstAnalyticalUnitId, string instrumentID)
            {
                m_InstAnalyticalUnitID = InstAnalyticalUnitId;
                m_instrumentID = instrumentID;
            }

        }

        #endregion

        #region Public Shared Methods
        public static InstAnalyticalUnit CreateInstAnalyticalUnit(int InstAnalyticalUnitID)
        {
            var objInstAnalyticalUnit = Fetch(InstAnalyticalUnitID);

            if (objInstAnalyticalUnit == null)
            {
                objInstAnalyticalUnit = new InstAnalyticalUnit(InstAnalyticalUnitID);
            }

            return objInstAnalyticalUnit;
        }

        public static InstAnalyticalUnit Fetch(int InstAnalyticalUnitID)
        {


            // Dim objInstAnalyticalUnit As InstAnalyticalUnit = DataFactory.Fetch(New Criteria(InstAnalyticalUnitID))

            return (InstAnalyticalUnit)DataFactory.Fetch(new Criteria(InstAnalyticalUnitID));

            // If objInstAnalyticalUnit Is Nothing OrElse objInstAnalyticalUnit.AnalyticalUnitID = 0 Then
            // Return objInstAnalyticalUnit
            // End If
            // Return objInstAnalyticalUnit
        }

        public static InstAnalyticalUnit FetchByInstrumentID(string instrumentID)
        {
            // Dim objInstAnalyticalUnit As InstAnalyticalUnit = DataFactory.Fetch(New Criteria(0, instrumentID))
            // If objInstAnalyticalUnit Is Nothing OrElse objInstAnalyticalUnit.AnalyticalUnitID = 0 Then
            // Return objInstAnalyticalUnit
            // End If
            // Return objInstAnalyticalUnit

            return (InstAnalyticalUnit)DataFactory.Fetch(new Criteria(0, instrumentID));
        }

        #endregion



        #region  Overridden Methods 

        protected override void DataFactory_Fetch(object criteria)
        {
            try
            {
                Criteria c = (Criteria)criteria;
                var @params = new List<DbParameter>();
                DataTable[] dt = null;
                var dw = new DataWrapper(Configuration.ConnectionString);

                @params.Add((DbParameter)dw.CreateParameter("@AnalyticalUnitID", DbType.Int32, c.InstAnalyticalUnitID));
                @params.Add((DbParameter)dw.CreateParameter("@InstrumentId", DbType.String, c.InstrumentID));
                dt = dw.ExecuteProcedure("lis_InstAnalyticalUnit_FetchByAnalyticalUnitID", @params.ToArray());

                if (dt is not null && dt.Length > 0 && dt[0].Rows.Count > 0)
                {
                    Load(dt[0].Rows[0]);
                }
            }

            catch (Exception ex)
            {
                throw ex;
            }
        }

        public void Load(DataRow row)
        {
            try
            {
                m_analyticalunitid = Conversions.ToInteger(row["AnalyticalUnitID"]);

                m_analyzerid = Conversions.ToInteger(row["AnalyzerId"]);
                m_analyticalunitname = Conversions.ToString(row["AnalyticalUnitName"]);
                m_instrumentid = Conversions.ToString(row["InstrumentId"]);
                m_analyticalunitserial = Conversions.ToString(row["AnalyticalUnitSerial"]);
                m_isdeleted = Conversions.ToBoolean(Conversions.ToString(row["IsDeleted"]));

                m_createdby = Conversions.ToString(row["CreatedBy"]);
                m_createddate = Conversions.ToDate(row["CreatedDate"]);

                if (row["UpdatedDate"] is DBNull)
                {
                    m_updateddate = Conversions.ToDate(row["CreatedDate"]);
                }
                else
                {
                    m_updateddate = Conversions.ToDate(row["UpdatedDate"]);
                }

                if (row["UpdatedBy"] is DBNull)
                {
                    m_updatedby = Conversions.ToString(row["CreatedBy"]);
                }
                else
                {
                    m_updatedby = Conversions.ToString(row["UpdatedBy"]);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void DataFactory_Save()
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();

            try
            {
                var options = new TransactionOptions();
                options.IsolationLevel = System.Transactions.IsolationLevel.ReadUncommitted;
                options.Timeout = new TimeSpan(0, 2, 0);

                using (var scope = new TransactionScope(TransactionScopeOption.Required, options))
                {

                    @params.Add((DbParameter)dw.CreateParameter("@AnalyticalUnitID", DbType.Int32, AnalyticalUnitID, ParameterDirection.InputOutput));
                    @params.Add((DbParameter)dw.CreateParameter("@AnalyzerId", DbType.Int32, AnalyzerId));
                    @params.Add((DbParameter)dw.CreateParameter("@AnalyticalUnitName", DbType.String, AnalyticalUnitName));
                    @params.Add((DbParameter)dw.CreateParameter("@InstrumentId", DbType.String, InstrumentId));
                    @params.Add((DbParameter)dw.CreateParameter("@AnalyticalUnitSerial", DbType.String, AnalyticalUnitSerial));
                    @params.Add((DbParameter)dw.CreateParameter("@IsDeleted", DbType.Boolean, IsDeleted));

                    @params.Add((DbParameter)dw.CreateParameter("@UpdatedBy", DbType.String, UpdatedBy));

                    m_analyticalunitid = Conversions.ToInteger(dw.ExecuteNonQuery("lis_InstAnalyticalUnit_Save", @params.ToArray())["@AnalyticalUnitID"].Value);
                    scope.Complete();

                }
            }

            catch (Exception ex)
            {
                throw ex;
            }

        }
        #endregion

    }
}