using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Transactions;
using Bioreference.Data;
using Bioreference.Data.Audit;
using Bioreference.Data.Client;
using Microsoft.VisualBasic.CompilerServices;

namespace Bioreference.LIS
{

    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 
    // 
    [Serializable()]
    public class InstGroup : AuditDataClassBase
    {

        #region  Private Members 

        private int m_instrumentgroupid;
        private string m_instrumentgroupname;
        private bool m_isdeleted;
        private DateTime m_createddate;
        private string m_createdby;
        private DateTime m_updateddate;
        private string m_updatedby;

        private InstAnalyzers m_objAnalyzers;

        #endregion

        #region  Public Properties 


        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property InstrumentGroupId
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public int InstrumentGroupId
        {
            get
            {
                return m_instrumentgroupid;
            }
            set
            {
                m_instrumentgroupid = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property InstrumentGroupName
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string InstrumentGroupName
        {
            get
            {
                return m_instrumentgroupname;
            }
            set
            {
                m_instrumentgroupname = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property IsDeleted
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public bool IsDeleted
        {
            get
            {
                return m_isdeleted;
            }
            set
            {
                m_isdeleted = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property CreatedDate
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public DateTime CreatedDate
        {
            get
            {
                return m_createddate;
            }
            set
            {
                m_createddate = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property CreatedBy
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string CreatedBy
        {
            get
            {
                return m_createdby;
            }
            set
            {
                m_createdby = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property UpdatedDate
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public DateTime UpdatedDate
        {
            get
            {
                return m_updateddate;
            }
            set
            {
                m_updateddate = value;
            }
        }



        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property UpdatedBy
        // '''''''''''''''''''''''''''''''''''''''''''''    
        public string UpdatedBy
        {
            get
            {
                return m_updatedby;
            }
            set
            {
                m_updatedby = value;
            }
        }

        // '''''''''''''''''''''''''''''''''''''''''''''
        // ''''' Property InstAnalyzerList
        // '''''''''''''''''''''''''''''''''''''''''''''
        public InstAnalyzers InstAnalyzerList
        {
            get
            {
                return m_objAnalyzers;
            }
        }


        #endregion

        #region  Overridden Properties 

        public override object IdentifierId
        {
            get
            {
                return m_instrumentgroupid;
            }
        }

        #endregion

        #region Constructor

        internal InstGroup()
        {
            m_objAnalyzers = new InstAnalyzers(this);
            FlagDirty();
        }

        internal InstGroup(int Inst_InstrumentGroupID)
        {
            m_instrumentgroupid = Inst_InstrumentGroupID;
            m_objAnalyzers = new InstAnalyzers(this);
            FlagDirty();
        }

        #endregion

        #region  Criteria Class 
        [Serializable()]
        internal class Criteria
        {
            private int m_Inst_InstrumentGroupID;

            public int Inst_InstrumentGroupID
            {
                get
                {
                    return m_Inst_InstrumentGroupID;
                }
            }

            public Criteria(int Inst_InstrumentGroupId)
            {
                m_Inst_InstrumentGroupID = Inst_InstrumentGroupId;
            }

        }

        #endregion

        #region Public Shared Methods

        private string SP_GROUP_FETCHBYINSTRUMID { get; set; }

        public static InstGroup CreateInstGroup(int Inst_InstrumentGroupID)
        {
            var objInst_InstrumentGroup = Fetch(Inst_InstrumentGroupID);

            if (objInst_InstrumentGroup == null)
            {
                objInst_InstrumentGroup = new InstGroup(Inst_InstrumentGroupID);
            }

            return objInst_InstrumentGroup;
        }

        public static InstGroup Fetch(int Inst_InstrumentGroupID)
        {
            InstGroup objInst_InstrumentGroup = (InstGroup)DataFactory.Fetch(new Criteria(Inst_InstrumentGroupID));
            if (objInst_InstrumentGroup is null || objInst_InstrumentGroup.InstrumentGroupId == 0)
            {
                return null;
            }
            else
            {
                return objInst_InstrumentGroup;
            }
        }

        #endregion

        public InstAnalyzer CreateAnalyzer()
        {
            // create a Child, add it to the specimen list and return it
            var objChild = new InstAnalyzer(this);
            m_objAnalyzers.List.Add(objChild);
            return objChild;
        }

        #region  Overridden Methods 

        protected override void DataFactory_Fetch(object criteria)
        {
            try
            {
                Criteria c = (Criteria)criteria;
                var @params = new List<DbParameter>();
                DataTable[] dt = null;
                var dw = new DataWrapper(Configuration.ConnectionString);

                @params.Add((DbParameter)dw.CreateParameter("@InstrumentGroupID", DbType.Int32, c.Inst_InstrumentGroupID));
                dt = dw.ExecuteProcedure("lis_InstGroup_FetchByInstrumentGroupID", @params.ToArray());

                if (dt is not null && dt.Length > 0 && dt[0].Rows.Count > 0)
                {
                    Load(dt[0].Rows[0]);
                }

                FetchAnalyzers(m_instrumentgroupid);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public void Load(DataRow row)
        {
            try
            {
                m_instrumentgroupid = Conversions.ToInteger(row["InstrumentGroupID"]);
                m_instrumentgroupname = Conversions.ToString(row["InstrumentGroupName"]);
                m_createdby = Conversions.ToString(row["CreatedBy"]);
                m_createddate = Conversions.ToDate(row["CreatedDate"]);

                if (row["UpdatedDate"] is DBNull)
                {
                    m_updateddate = Conversions.ToDate(row["CreatedDate"]);
                }
                else
                {
                    m_updateddate = Conversions.ToDate(row["UpdatedDate"]);
                }

                if (row["UpdatedBy"] is DBNull)
                {
                    m_updatedby = Conversions.ToString(row["CreatedBy"]);
                }
                else
                {
                    m_updatedby = Conversions.ToString(row["UpdatedBy"]);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        private void FetchAnalyzers(int Inst_InstrumentGroupID)
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();
            try
            {
                @params.Add((DbParameter)dw.CreateParameter("@InstrumentGroupID", DbType.Int32, Inst_InstrumentGroupID));
                DataTable[] dt = dw.ExecuteProcedure("lis_InstAnalyzer_FetchByInstrumentGroupID", @params.ToArray());
                if (dt[0].Rows.Count > 0)
                {
                    m_objAnalyzers.Load(dt);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        protected override void DataFactory_Save()
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();
            try
            {
                var options = new TransactionOptions();
                options.IsolationLevel = System.Transactions.IsolationLevel.ReadUncommitted;
                options.Timeout = new TimeSpan(0, 2, 0);

                using (var scope = new TransactionScope(TransactionScopeOption.Required, options))
                {
                    @params.Add((DbParameter)dw.CreateParameter("@InstrumentGroupID", DbType.Int32, InstrumentGroupId, ParameterDirection.InputOutput));
                    @params.Add((DbParameter)dw.CreateParameter("@InstrumentGroupName", DbType.String, InstrumentGroupName));
                    @params.Add((DbParameter)dw.CreateParameter("@IsDeleted", DbType.Boolean, IsDeleted));
                    @params.Add((DbParameter)dw.CreateParameter("@UpdatedBy", DbType.String, UpdatedBy));

                    m_instrumentgroupid = Conversions.ToInteger(dw.ExecuteNonQuery("lis_InstGroup_Save", @params.ToArray())["@InstrumentGroupID"].Value);

                    if (!IsDeleted)
                    {
                        foreach (InstAnalyzer objAnalyzer in m_objAnalyzers.List)
                            objAnalyzer.InstrumentGroupId = m_instrumentgroupid;
                        m_objAnalyzers.List.Update();
                    }
                    scope.Complete();

                }
            }

            catch (Exception ex)
            {
                throw ex;
            }

        }
        #endregion

    }
}