using System;
using Bioreference.Data;

namespace Bioreference.LIS
{


    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014
    // 
    [Serializable()]
    public class InstGroupList : DataClassCollectionBase
    {

        internal InstGroupList()
        {
        }

        internal void Add(InstGroup inst_instrumentgroup)
        {

            List.Add(inst_instrumentgroup);

        }

        public void Insert(int index, InstGroup inst_instrumentgroup)
        {
            List.Insert(index, inst_instrumentgroup);
        }

        internal void Remove(InstGroup inst_instrumentgroup)
        {

            List.Remove(inst_instrumentgroup);

        }

        public InstGroup this[int index]
        {
            get
            {
                return (InstGroup)List[index];
            }
        }

        internal void Update()
        {

            foreach (InstGroup w in List)
                w.Save();

            // For Each w As Inst_InstrumentGroup In MyBase.DeletedItemsList
            // w.Delete()
            // Next

        }

        public override bool IsDirty
        {
            get
            {
                if (!(DeletedItemsList == null) && DeletedItemsList.Count > 0)
                    return true;

                foreach (InstGroup w in List)
                {
                    if (w.IsDirty)
                        return true;
                }

                return false;
            }
        }

    }
}