using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Bioreference.Data;
using Bioreference.Data.Client;

namespace Bioreference.LIS
{

    // 
    // Generated By: Victor Castro-Castillo
    // Date: 7/28/2014 3:27:20 PM
    // 
    [Serializable()]
    public class InstAnalyticalUnits : DataClassBase
    {

        #region  Private Members 

        private InstAnalyticalUnitList m_list;
        private InstAnalyzer m_parent;

        #endregion

        #region  Public Properties 

        public InstAnalyticalUnitList List
        {
            get
            {
                return m_list;
            }
        }

        #endregion

        #region  Constructor 

        private InstAnalyticalUnits()
        {
            m_list = new InstAnalyticalUnitList();
        }

        internal InstAnalyticalUnits(InstAnalyzer parent)
        {
            m_parent = parent;
            m_list = new InstAnalyticalUnitList();
        }
        #endregion

        #region  Criteria Class 
        [Serializable()]
        internal class Criteria
        {
            public Criteria(int instrumentAnalyzerID)
            {
                m_intrumentAnalyzerID = instrumentAnalyzerID;
            }

            private int m_intrumentAnalyzerID;
            public int InstrumentAnalyzerID
            {
                get
                {
                    return m_intrumentAnalyzerID;
                }
                set
                {
                    m_intrumentAnalyzerID = value;
                }
            }
        }
        #endregion

        #region  Public Methods 
        // retrieves all InstAnalyticalUnits
        public static InstAnalyticalUnits Fetch(int analyzerID)
        {
            InstAnalyticalUnits objInstAnalyticalUnits = (InstAnalyticalUnits)DataFactory.Fetch(new Criteria(analyzerID));
            return objInstAnalyticalUnits;
        }

        #endregion


        #region  Overridden Methods 

        protected override void DataFactory_Fetch(object criteria)
        {
            var dw = new DataWrapper(Configuration.ConnectionString);
            var @params = new List<DbParameter>();
            Criteria crit = (Criteria)criteria;
            try
            {
                @params.Add((DbParameter)dw.CreateParameter("@AnalyzerID", DbType.String, crit.InstrumentAnalyzerID));
                DataTable[] dt = dw.ExecuteProcedure("lis_InstAnalyticalUnit_FetchByAnalyzerID", @params.ToArray());
                if (dt[0].Rows.Count > 0)
                {
                    Load(dt);
                }
            }

            catch (Exception ex)
            {
                throw ex;
            }
        }

        #endregion

        #region  Private Methods 

        internal void Load(DataTable[] dt)
        {
            InstAnalyticalUnit objInstAnalyticalUnit = null;
            {
                ref var withBlock = ref dt[0];
                foreach (DataRow dr in withBlock.Rows)
                {
                    objInstAnalyticalUnit = new InstAnalyticalUnit();
                    objInstAnalyticalUnit.Load(dr);
                    m_list.Add(objInstAnalyticalUnit);
                }
            }
        }

        #endregion
    }
}