using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Bioreference.Common.Lab;
using Bioreference.Common.TestMaster;
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '
// '  OrderAnalytePanel.vb
// '  Implementation of the Class OrderAnalytePanel
// '  Generated by Enterprise Architect
// '  Created on:      31-Jan-2008 5:13:15 PM
// '  Original author: Angelo Galeotafiore
// '  
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '  Modification history:
// '  
// '
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

using Bioreference.Data.Audit;
using Bioreference.Data.Client;
using log4net;
using Microsoft.VisualBasic;
using Microsoft.VisualBasic.CompilerServices;

namespace Bioreference.LIS
{

    [Serializable()]
    public class ReportAnalytePanel : AuditDataClassBase
    {

        #region Private Members

        private long m_id = 0L;
        private Report m_parent = null;
        private ReportComments m_comments = null;
        private ReportAnalytes m_orderAnalytes = null;
        private string m_panelCode = "";
        private List<string> m_orderingPanelCodes = new List<string>();
        private RefAnalytePanel m_panel = null;
        private transmitStatusType m_transmitStatus = transmitStatusType.PendingRelease;
        internal transmitStatusType m_onLoadTransmitStatus;
        private criticalType m_criticalType = criticalType.NotEvaluated;
        private bool m_resetReleaseDate = false; // This gets set to True when an Panel is set to Release. The date is then set on the server.
        private DateTime m_releaseDate = DateTime.Parse("1900-01-01");
        private bool m_isPreliminaryReleased = false;
        private bool m_markedAsPreliminary = false;
        private List<string> m_auditItemList;
        private bool m_toFollowSent;
        private long m_SPMOrderTestId;
        private bool m_IsProcessing = false;
        private bool m_releaseFromUI;
        private bool m_isDeleted = false; // Need this to track if a ReportAnalyte is deleted. A report analyte can be updated even if deleted (ex. demographic updates)
        private int m_spmStatus = 0;
        private string m_parentTestCode = "";
        private static readonly ILog Logger = LogManager.GetLogger<ReportAnalytePanel>();

        #endregion

        #region Constructor

        internal ReportAnalytePanel(Report parent, TestAnalytePanel panel, string orderingPanelCode, SPMStatusValue spmStatus)
        {
            m_onLoadTransmitStatus = m_transmitStatus;
            m_auditItemList = new List<string>();
            m_parent = parent;
            m_panelCode = panel.PanelCode;
            m_spmStatus = (int)spmStatus;
            AddOrderingCode(orderingPanelCode);

            m_panel = new RefAnalytePanel(this);
            m_panel.Load(panel);
            // m_panel = panel

            m_comments = new ReportComments(this);
            m_orderAnalytes = new ReportAnalytes(this);
            // 'Code here create an OrderAnalytePanel from an AnalytePanel
            // ************************************************************
            foreach (Analyte a in panel.Analytes.List)
            {
                var oa = new ReportAnalyte(this, (TestAnalyte)a, "", spmStatus: spmStatus);
                Analytes.List.Add(oa);
            }
            // ************************************************************

            // Moved here so rules can fire properly
            parent.AnalytePanels.List.Add(this);

            // 'We do this after since we may need all the analytes when firing a rule.
            foreach (ReportAnalyte a in Analytes.List)
            {
                if (a.Analyte.IsRequired)
                {
                    Logger.Debug($"Calling EvaluateRulesEx with RuleSetRelease on {a.Code}");
                    parent.EvaluateRulesEx(a, "", Configuration.RuleSetRelease);
                }
            }
            InitializeToFollowSent(false);
            FlagDirty();
            FlagChild();
        }

        internal ReportAnalytePanel(Report parent, TestInfo testInfo, string orderingPanelCode, SPMStatusValue spmStatus)
        {
            m_onLoadTransmitStatus = m_transmitStatus;
            m_auditItemList = new List<string>();
            m_parent = parent;
            m_panelCode = testInfo.Code;
            m_spmStatus = (int)spmStatus;
            AddOrderingCode(orderingPanelCode);

            m_panel = new RefAnalytePanel(this);
            m_panel.Load(testInfo);
            // m_panel = panel

            m_comments = new ReportComments(this);
            m_orderAnalytes = new ReportAnalytes(this);
            // 'Code here create an OrderAnalytePanel from an AnalytePanel
            // ************************************************************
            foreach (TestInfo ti in testInfo.Components)
            {
                var oa = new ReportAnalyte(this, ti, "", spmStatus: spmStatus);
                Analytes.List.Add(oa);
            }

            // Moved here so rules can fire properly
            parent.AnalytePanels.List.Add(this);

            // 'We do this after since we may need all the analytes when firing a rule.
            foreach (ReportAnalyte a in Analytes.List)
            {
                if (a.Analyte.IsRequired)
                {
                    Logger.Debug("Calling EvaluateRulesEx with RuleSetRelease");
                    parent.EvaluateRulesEx(a, "", Configuration.RuleSetRelease);
                }
            }
            // ************************************************************
            InitializeToFollowSent(testInfo.DoNotSendToFollow);
            FlagDirty();
            FlagChild();
        }

        // Use this sub new to load an OrderAnalytePanel from the db.
        internal ReportAnalytePanel(Report parent, bool loadAudit = false)
        {
            m_onLoadTransmitStatus = m_transmitStatus;
            m_auditItemList = new List<string>();
            m_parent = parent;
            m_comments = new ReportComments(this);
            m_orderAnalytes = new ReportAnalytes(this);
            LoadAudit = loadAudit;
            InitializeToFollowSent(false);
            FlagChild();
        }

        // Friend Sub SetPanel(ByVal panel As AnalytePanel)
        // m_panel = panel
        // End Sub

        #endregion


        #region Events

        public delegate void UpdatePanelDelegate(ReportAnalytePanel panel, EventArgs arg);

        [NonSerialized()]
        private List<UpdatePanelDelegate> mNonSerializableHandlers = new List<UpdatePanelDelegate>();

        // We need to declare this custom event because we need to mark the delegates as nonSerializable - so
        // that the target object will not be attempted to be serialized.
        public event UpdatePanelDelegate UpdatePanelCompleted
        {

            add
            {

                if (mNonSerializableHandlers is null)
                {
                    mNonSerializableHandlers = new List<UpdatePanelDelegate>();
                }

                mNonSerializableHandlers.Add(value);

            }

            remove
            {

                if (!(mNonSerializableHandlers == null))
                {
                    mNonSerializableHandlers.Remove(value);
                }

            }

        }

        void OnUpdatePanelCompleted(ReportAnalytePanel panel, EventArgs arg)
        {
            if (!(mNonSerializableHandlers == null))
            {
                foreach (UpdatePanelDelegate item in mNonSerializableHandlers)
                    item.Invoke(panel, arg);
            }
        }

        public delegate void UpdatedReportAnalytePanelDelegate(ReportAnalytePanel panel, ReportAnalytePanelUpdatedArg arg);
        public event UpdatedReportAnalytePanelDelegate CommentChanged;

        [Serializable()]
        public class ReportAnalytePanelUpdatedArg : EventArgs
        {

            private List<ReportComment> m_comment;
            private bool m_isCommentUpdated = false;

            public List<ReportComment> Comments
            {
                get
                {
                    return m_comment;
                }
            }

            public ReportAnalytePanelUpdatedArg(List<ReportComment> comment)
            {
                if (comment is not null)
                {
                    m_isCommentUpdated = true;
                    m_comment = comment;
                }
                else
                {
                    m_isCommentUpdated = false;
                }
            }



            public bool IsCommentUpdated
            {
                get
                {
                    if (m_comment is not null && m_comment.Count > 0)
                    {
                        return m_isCommentUpdated;
                    }
                    return false;
                }
            }

        }

        protected internal void Updated(ReportAnalytePanelUpdatedArg e)
        {
            // If Not IsNothing(Changed) Then
            CommentChanged?.Invoke(this, e);
            // End If
        }


        #endregion

        // Friend Sub SetReferenceLab(ByVal referenceLabId As Integer, ByVal referenceLabTestCode As String)

        // If IsNothing(m_panel) Then m_panel = New RefAnalytePanel(Me)
        // 'm_panel.PanelCode = String.Format("{0}-{1}", referenceLabId, referenceLabTestCode)
        // m_panel.ReferenceLabId = referenceLabId
        // m_panel.ReferenceLabCode = referenceLabTestCode
        // Me.FlagDirty()

        // End Sub

        private void InitializeToFollowSent(bool notSendToFollow)
        {
            // ''''''''''''''''''''''''''''' To Follow'''''''''''''''''''''''''''''''''''''''''''''''''''''''''
            if (!Configuration.AppSettings.GetBool("Bioreference.LIS:ToFollowEnabled"))
            {
                m_toFollowSent = true;
                foreach (ReportAnalyte a in Analytes.List)
                    a.ToFollowSent = true;
                return;
            }

            if (!(m_parent == null) && m_parent.IsCOC)
            {
                m_toFollowSent = true;
            }
            // ElseIf Not IsNothing(m_panel) AndAlso m_panel.Category.ToLower().Equals("allergen") Then
            // Me.m_toFollowSent = True
            else if (!(m_panel == null) && m_panel.IsReportable && !notSendToFollow)
            {
                m_toFollowSent = false;
            }
            else
            {
                m_toFollowSent = true;
            }
            // '''' Loop on eachh analyte for the panel
            foreach (ReportAnalyte a in Analytes.List)
            {
                if (notSendToFollow)
                {
                    a.ToFollowSent = true;
                }
                else if (!(m_parent == null) && m_parent.IsCOC)
                {
                    a.ToFollowSent = true;
                }
                // ElseIf Not IsNothing(a) AndAlso a.Analyte.Category.ToLower().Equals("allergen") Then
                // a.ToFollowSent = True
                else if (!(a == null) && a.Analyte.IsReportable && a.Analyte.IsRequired)
                {
                    a.ToFollowSent = false;
                }
                else
                {
                    a.ToFollowSent = true;
                }
            }

            // ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
        }

        internal void SetFinal()
        {

            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                if (!string.IsNullOrEmpty(a.ResultValue))
                {
                    a.ResultStatus = resultStatusType.Final;
                }
            }

        }

        internal void SetCriticalType(criticalType @type)
        {

            if (m_criticalType != type)
            {
                m_criticalType = type;
                FlagDirty();
            }

        }

        public void ProcessTNPFromReporting4k()
        {
            RemoveAllComments();
        }

        public void AddCommentForCommentUpdate(string commenttype)
        {
            if (HasBeenReleased())
            {
                AddComment(Conversions.ToString(FormatCommentForCommentUpdate(Configuration.LISSettings.GetString("AutomatedRevisedComment"), commenttype)));
            }
        }

        public object FormatCommentForCommentUpdate(string commenttext, string commenttype)
        {
            string Comment = "";
            if (commenttype == "Add")
            {
                Comment = string.Format(commenttext, "added to", Strings.Format(ReleaseDate, "MM/dd/yyyy"));
            }
            else if (commenttype == "Delete")
            {
                Comment = string.Format(commenttext, "deleted from", Strings.Format(ReleaseDate, "MM/dd/yyyy"));
            }
            return SharedFunctions.FormatCommentText(Comment, Configuration.LISSettings.GetInt("CommentUpdateMaxLength"));

        }

        public void RemoveAllComments()
        {
            foreach (ReportComment c in Comments.List)
            {
                Comments.List.Remove(c);
                RemoveAllComments();
                break;
            }
        }

        public void SetStatusToCorrected()
        {
            if (IsTestHold())
            {
                return;
            }
            foreach (ReportAnalyte a in Analytes.List)
            {
                // NA: When changing the status need to set the transmit status as well
                // If a.ResultStatus = resultStatusType.Final Then a.ResultStatus = resultStatusType.Corrected
                if (a.ResultStatus == resultStatusType.Final)
                {
                    a.ResultStatus = resultStatusType.Corrected;
                    a.SetTransmitStatus(transmitStatusType.PendingRelease);
                }
            }

        }

        [Obsolete("Needs to be changed, cannot have direct access to TransmitStatus")]
        internal void SetTransmitStatus(transmitStatusType status, bool updateAnalytes = true)
        {
            if (status != m_transmitStatus)
            {
                if (IsTestHold() & status > transmitStatusType.PendingRelease)
                {
                    return;
                }
                m_transmitStatus = status;
                if (status == transmitStatusType.Released)
                {
                    m_resetReleaseDate = true;
                    m_isPreliminaryReleased = false;
                }

                if (updateAnalytes)
                {
                    foreach (ReportAnalyte a in m_orderAnalytes.List)
                        a.SetTransmitStatus(status);
                }
                FlagDirty();
            }
        }

        #region Public Functions

        public void SetAccessioningFacility(string facilityCode)
        {

            foreach (ReportAnalyte a in Analytes.List)
                a.SetAccessioningFacility(facilityCode);

        }

        public void SetPreliminaryReleased(bool val)
        {
            m_isPreliminaryReleased = val;
            if (!val)
            {
                m_releaseDate = DateTime.Parse("1900-01-01");
            }
        }

        public bool CheckIfSampleReceived()
        {
            bool returnval = false;
            var r = m_parent;
            if (r.ReferencedOrder.SpecimenUpdated && m_parent is Report)
            {
                foreach (ReportAnalyte a in Analytes.List)
                {
                    if (r.ReferencedOrder.IsHospitalAccount() && a.HasSampleRequest())
                    {
                        returnval = true;
                        break;
                    }
                }
            }
            return returnval;
        }

        public bool CanPrelimRelease()
        {
            return ((RefAnalytePanel)Panel).AllowPreliminaryRelease && IsPartiallyResulted();
        }

        public bool PanelIsPartiallyResulted()
        {
            return IsPartiallyResulted();
        }

        private bool IsPartiallyResulted()
        {
            int totalCount = 0;
            int resultedCount = 0;
            foreach (ReportAnalyte analyte in Analytes.List)
            {
                if (analyte.Analyte.IsRequired)
                {
                    if (analyte.ResultStatus == resultStatusType.Final)
                    {
                        return false;
                    }
                    totalCount += 1;
                    if (!string.IsNullOrEmpty(analyte.ResultValue))
                    {
                        resultedCount += 1;
                    }
                }
                if (resultedCount != 0 && resultedCount < totalCount)
                {
                    return true;
                }
            }
            return false;
        }

        public void SetPerformingFacility(string facilityCode)
        {

            foreach (ReportAnalyte a in Analytes.List)
                a.SetPerformingFacility(facilityCode);

        }

        public void SetAnalyteSpecimenCodes(string specimenCodes)
        {

            foreach (ReportAnalyte a in Analytes.List)
            {
                a.SpecimenCodes = specimenCodes;
                Logger.Debug($"--> Panel:{PanelCode}, Analyte:{a.Code}, SpecimenCodes:{a.SpecimenCodes}");
            }

        }

        public bool ContainsOrderCode(string testCode)
        {

            return m_orderingPanelCodes.Contains(testCode);

        }

        public void AddOrderingCode(string testCode)
        {

            if (testCode.Equals(""))
                return;

            if (!m_orderingPanelCodes.Contains(testCode))
            {
                m_orderingPanelCodes.Add(testCode);

                if (HasBeenReleased())
                    MarkAsReleased();

                FlagDirty();
            }

        }

        public void RemoveOrderingCodes()
        {
            m_orderingPanelCodes.Clear();
        }

        public void RemoveOrderingCode(string testCode, bool deleteTestWithNoOrderables = true)
        {

            if (testCode.Equals(""))
                return;

            m_orderingPanelCodes.Remove(testCode);
            FlagDirty();

            if (deleteTestWithNoOrderables)
            {
                if (m_orderingPanelCodes.Count == 0)
                {
                    Parent.RemovePanel((int)Id);
                }
            }

        }

        /// <summary>
    /// Used to raise events
    /// </summary>
    /// <param name="comment"></param>
    /// <returns></returns>
    /// <remarks></remarks>
        public ReportComment AddComment(string comment)
        {

            var r = Comments.AddComment(comment, "C", false, "", ExternalCommentType.Comment);
            OnUpdatePanelCompleted(this, EventArgs.Empty);
            return r;

        }

        public ReportComment AddCommentWithoutExternalId(string comment)
        {

            var r = Comments.AddComment(comment, "", false, "", ExternalCommentType.Comment);
            OnUpdatePanelCompleted(this, EventArgs.Empty);
            return r;

        }

        public void DeleteComment(ReportComment comment, bool changeStatus = true)
        {

            Comments.DeleteComment(comment, changeStatus);
            OnUpdatePanelCompleted(this, EventArgs.Empty);

        }

        /// <summary>
    /// Exception will be thrown if ResultStatus is not SentToReporting.
    /// </summary>
    /// <remarks></remarks>
        public void MarkAsReported()
        {
            if (!IsTestHold() && m_transmitStatus == transmitStatusType.SentToReporting)
            {
                foreach (ReportAnalyte a in m_orderAnalytes.List)
                    a.MarkAsReported();
                m_transmitStatus = transmitStatusType.Reported;
                FlagDirty();
                // Else
                // Throw New Exception(String.Concat("Unable to set status to Reported if status is ", m_transmitStatus))
            }
        }

        /// <summary>
    /// Exception will be thrown if ResultStatus is not SentToReporting.
    /// </summary>
    /// <remarks></remarks>
        public void MarkAsReadByReporting()
        {
            if (!IsTestHold() && m_transmitStatus == transmitStatusType.SentToReporting)
            {
                foreach (ReportAnalyte a in m_orderAnalytes.List)
                    a.MarkAsReadByReporting();
                m_transmitStatus = transmitStatusType.ReadByReporting;
                FlagDirty();
            }
            else
            {
                throw new Exception(string.Concat("Unable to set status to ReadByReporting if status is ", m_transmitStatus));
            }
        }

        /// <summary>
    /// Exception will be thrown if ResultStatus is not ReadByReporting.
    /// </summary>
    /// <remarks></remarks>
        public void MarkAsStatusSentToVertex()
        {

            if (IsPreliminaryReleased)
            {
                throw new Exception("Unable to set status to SentToVertex when panel is partially released.");
            }

            if (!IsTestHold() && (m_transmitStatus == transmitStatusType.ReadByReporting || m_transmitStatus == transmitStatusType.SentToReporting))
            {
                foreach (ReportAnalyte a in m_orderAnalytes.List)
                    a.MarkAsStatusSentToVertex();
                m_transmitStatus = transmitStatusType.StatusSentToVertex;
                FlagDirty();
            }
            else
            {
                throw new Exception(string.Concat("Unable to set status to StatusSentToVertex if status is ", m_transmitStatus));
            }
        }

        /// <summary>
    /// Exception will be thrown if ResultStatus is not Released Or SentToReporting.
    /// </summary>
    /// <remarks></remarks>
        public void MarkAsSentToReporting()
        {
            if (!IsTestHold() && (m_transmitStatus == transmitStatusType.SentToReporting || m_transmitStatus == transmitStatusType.Released))
            {
                foreach (ReportAnalyte a in m_orderAnalytes.List)
                    a.MarkAsSentToReporting();
                m_transmitStatus = transmitStatusType.SentToReporting;
                FlagDirty();
            }
            else
            {
                throw new Exception(string.Concat("Unable to set status to SentToReporting if status is ", m_transmitStatus));
            }
        }

        /// <summary>
    /// </summary>
    /// <remarks></remarks>
        public void MarkAsReleased()
        {
            // Removed if condition - need to be able to rerelease
            // If m_transmitStatus = transmitStatusType.PendingRelease OrElse m_transmitStatus = transmitStatusType.Released Then
            bool releaseFromUI;
            if (MarkedAsPreliminary)
            {
                MarkAsPreliminaryReleasedOnCondition((List<string>)Configuration.LISSettings.GetList("TestCodeListForPrelimRelease"));
            }
            else
            {
                foreach (ReportAnalyte a in m_orderAnalytes.List)
                {
                    releaseFromUI = a.ReleaseFromUI;
                    if (!string.IsNullOrEmpty(a.ResultValue))
                    {
                        if (m_releaseFromUI)
                        {
                            a.ReleaseFromUI = true;
                        }
                        a.MarkAsReleased();
                        if (a.IsDeltaHold)
                            a.ReleaseFromUI = releaseFromUI;
                    }
                }
                Logger.Debug($"Panel {PanelCode} IsTestHold={IsTestHold()}");
                if (!IsTestHold())
                {
                    Logger.Debug($"Panel {PanelCode} Releasing");
                    m_resetReleaseDate = true;
                    if (AnalytesReadyForRelease())
                        m_transmitStatus = transmitStatusType.Released;
                    m_isPreliminaryReleased = false;
                }
                FlagDirty();
            }
            // Else
            // Throw New Exception(String.Concat("Unable to set status to Released if status is ", m_transmitStatus))
            // End If
        }

        public void ReRelease(bool isCoc)
        {
            // only COC re-release is permitted for now via this route.
            if (!IsTestHold())
            {
                if (!isCoc)
                    return;

                foreach (ReportAnalyte a in m_orderAnalytes.List)
                {
                    if (!string.IsNullOrEmpty(a.ResultValue))
                        a.ReRelease(isCoc);
                }

                m_resetReleaseDate = true;
                if (AnalytesReadyForRelease())
                    m_transmitStatus = transmitStatusType.Released;
                m_isPreliminaryReleased = false;
                FlagDirty();
            }
        }

        /// <summary>
    /// Returns true if any analyte is in DeltaHold
    /// </summary>
    /// <returns></returns>
        public bool HoldReleaseForDeltaHold()
        {
            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                if (a.ResultStatus == resultStatusType.DeltaHold)
                {
                    Logger.Debug($"Panel {PanelCode} Analyte {a.Code} is DeltaHold");
                    return true;
                }
            }
            return false;
        }

        private bool AnalytesReadyForRelease()
        {
            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                if (a.Analyte.IsRequired && !a.HasBeenReleased())
                    return false;
            }
            return true;
        }

        public void MarkAsPreliminaryReleasedOnCondition(List<string> testCodeList)
        {
            if (!IsTestHold())
            {
                if (!((RefAnalytePanel)Panel).AllowPreliminaryRelease)
                {
                    throw new Exception("Unable to partial release a panel that does not allow partial releasing.");
                }

                foreach (ReportAnalyte a in m_orderAnalytes.List)
                {
                    if (!string.IsNullOrEmpty(a.ResultValue) && testCodeList.Contains(a.Code))
                        a.MarkAsPreliminaryReleased();
                }
                m_transmitStatus = transmitStatusType.Released;
                m_isPreliminaryReleased = true;
                m_resetReleaseDate = true;
                FlagDirty();
            }
        }

        public bool IsPanelSampleRequested()
        {
            bool returnval = false;
            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                if (!string.IsNullOrEmpty(a.ResultValue) && a.ResultValue == "QNS" && (a.SampleStatus == (int)SampleRequestType.SampleRequest || a.SampleStatus == (int)SampleRequestType.SampleEnRoute))
                {
                    returnval = true;
                    break;
                }
            }
            return returnval;
        }

        public void MarkAsPreliminaryReleased()
        {
            if (!IsTestHold())
            {
                if (!((RefAnalytePanel)Panel).AllowPreliminaryRelease && !IsPanelSampleRequested())
                {
                    throw new Exception("Unable to partial release a panel that does not allow partial releasing.");
                }

                foreach (ReportAnalyte a in m_orderAnalytes.List)
                {
                    if (!string.IsNullOrEmpty(a.ResultValue))
                        a.MarkAsPreliminaryReleased();
                }
                m_transmitStatus = transmitStatusType.Released;
                m_isPreliminaryReleased = true;
                m_resetReleaseDate = true;
                FlagDirty();
            }
        }

        /// <summary>
    /// Exception will be thrown if ResultStatus is not Released Or PendingRelased.
    /// </summary>
    /// <remarks></remarks>
        public void MarkAsPendingRelease()
        {
            if (m_transmitStatus == transmitStatusType.Released || m_transmitStatus == transmitStatusType.PendingRelease)
            {
                foreach (ReportAnalyte a in m_orderAnalytes.List)
                    a.MarkAsPendingReleased();
                m_transmitStatus = transmitStatusType.PendingRelease;
                FlagDirty();
            }
            else
            {
                throw new Exception(string.Concat("Unable to set status to PendingReleased if status is ", m_transmitStatus));
            }
        }

        /// <summary>
    /// derived from ReportAnalyte list
    /// </summary>
        public resultStatusType GetStatus()
        {

            int x = 0;
            int i = (int)resultStatusType.Final;

            if (m_orderAnalytes.List.Count == 0)
                return resultStatusType.Pending;

            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                if (a.Analyte.IsRequired)
                {
                    if (a.ResultStatus == resultStatusType.Corrected)
                        return resultStatusType.Corrected;
                    if (string.IsNullOrEmpty(a.ResultValue))
                        return resultStatusType.Pending; // 'For a result that was blanked out, then attempt to release panel
                    x = (int)a.ResultStatus;
                    if (x < i)
                        i = x;
                }
            }
            return (resultStatusType)i;
        }

        public bool IsTestHold()
        {
            if (m_orderAnalytes is null || m_orderAnalytes.List.Count == 0)
                return false;

            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                // AG 9/17/08 - We only care about Required analytes.
                if (a.Analyte.IsRequired)
                {
                    if (a.IsTestHold)
                        return true;
                }
            }
            return false;
        }

        public DateTime GetLatestResultDate()
        {

            var d = DateTime.Parse("1900-01-01");
            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                if (a.ResultDate > d)
                    d = a.ResultDate;
            }
            return d;

        }

        /// <summary>
    /// Determines if any result values have been reset prior to release.
    /// </summary>
    /// <returns></returns>
    /// <remarks></remarks>
        public bool HasPreviousResultValues()
        {

            foreach (ReportAnalyte a in m_orderAnalytes.List)
            {
                if (!string.IsNullOrEmpty(a.PreviousResultValue))
                    return true;
            }
            return false;

        }

        public bool HasBeenReleased()
        {
            if (IsTestHold())
            {
                return false;
            }
            else if (m_transmitStatus == transmitStatusType.Released || m_transmitStatus == transmitStatusType.StatusSentToVertex || m_transmitStatus == transmitStatusType.SentToReporting || m_transmitStatus == transmitStatusType.ReadByReporting || m_transmitStatus == transmitStatusType.Reported)



            {
                return true;
            }
            else
            {
                return false;
            }

        }

        public bool HasAlerts()
        {

            foreach (ReportAnalyte a in Analytes.List)
            {
                if (a.Alerts.List.Count > 0)
                    return true;
            }
            return false;

        }

        public void CheckProcessing()
        {
            if (!(HasBeenReleased() && GetStatus() >= resultStatusType.Final && GetStatus() != resultStatusType.OnHold))
            {
                m_IsProcessing = true;
            }
        }

        public bool HasAlertsThatBlockAutoRelease()
        {

            foreach (ReportAnalyte a in Analytes.List)
            {
                if (a.HasAlertsThatBlockAutoRelease())
                    return true;
            }
            return false;

        }

        #endregion

        #region Public Properties

        protected override long ObjectLookupIdentifier
        {
            get
            {
                return m_panel.Id;
            }
        }

        protected override object ParentIdentifierId
        {
            get
            {
                return m_parent.AccessionIdentifier;
            }
        }

        protected override parentIdentifierType ParentIdentifierType
        {
            get
            {
                return m_parent.AccessionIdentifierType;
            }
        }

        public bool IsPreliminaryReleased
        {
            get
            {
                return m_isPreliminaryReleased;
            }
        }

        public bool MarkedAsPreliminary
        {
            get
            {
                return m_markedAsPreliminary;
            }
            set
            {
                m_markedAsPreliminary = value;
                FlagDirty();
            }
        }

        public DateTime ReleaseDate
        {
            get
            {
                return m_releaseDate;
            }
        }

        [Audit("CriticalType")]
        public criticalType CriticalType
        {
            get
            {
                return m_criticalType;
            }
        }

        public Report Parent
        {
            get
            {
                return m_parent;
            }
        }

        public ReportAnalytes Analytes
        {
            get
            {
                return m_orderAnalytes;
            }
        }

        public AnalytePanel Panel
        {
            get
            {
                return m_panel;
            }
        }

        public ReportComments Comments
        {
            get
            {
                return m_comments;
            }
        }

        [Audit("TransmitStatus")]
        public transmitStatusType TransmitStatus
        {
            get
            {
                return m_transmitStatus;
            }
        }

        /// <summary>
    /// The Panel Code used by the consumer.
    /// </summary>
    /// <value></value>
    /// <returns></returns>
    /// <remarks></remarks>
        public string PanelCode
        {
            get
            {
                return m_panelCode;
            }
        }

        public string PanelName
        {
            get
            {
                return m_panel.Name;
            }
        }

        public string[] OrderingPanelCodes
        {
            get
            {
                return m_orderingPanelCodes.ToArray();
            }
        }

        [Audit("OrderingCodes")]
        public string OrderingCodes
        {
            get
            {
                return string.Join(",", m_orderingPanelCodes.ToArray());
            }
        }

        /// <summary>
    /// returns Base.IsDirty Or Comments Or OrderAnalytes
    /// </summary>
        public override bool IsDirty
        {
            get
            {
                return base.IsDirty || m_comments.IsDirty || m_orderAnalytes.IsDirty;
            }
        }

        public long Id
        {
            get
            {
                return m_id;
            }
        }

        public bool IsProcessing
        {
            get
            {
                return m_IsProcessing;
            }
        }

        public override object IdentifierId
        {
            get
            {
                return m_id;
            }
        }

        public bool ReleaseFromUI
        {
            get
            {
                return m_releaseFromUI;
            }
            set
            {
                m_releaseFromUI = value;
            }
        }

        // '*******************************************************
        // Security Implementation
        // 'Currently this is controlled by the UI.  This is not enforced by the object!

        private bool m_canRelease = true;
        private bool m_canWrite = true;
        private bool m_canRead = true;

        public bool CanRelease
        {
            get
            {
                foreach (ReportAnalyte a in Analytes.List)
                {
                    if (!a.CanRelease | a.IsTestHold)
                        return false;
                }
                return true;
            }
        }

        public bool CanRead
        {
            get
            {
                return m_canRead;
            }
            set
            {
                m_canRead = value;
            }
        }

        public bool CanWrite
        {
            get
            {
                return m_canWrite;
            }
            set
            {
                m_canWrite = value;
            }
        }
        // '*******************************************************

        public bool IsCorrected
        {
            get
            {
                foreach (ReportAnalyte a in Analytes.List)
                {
                    if (a.ResultStatus == resultStatusType.Corrected)
                        return true;
                }
                return false;
            }
        }

        public List<string> GetFormattedAuditItems
        {
            // get the audit item of this object as well as any object in the Save stream.
            get
            {
                return m_auditItemList;
            }
        }

        public bool ToFollowSent
        {
            get
            {
                return m_toFollowSent;
            }
            set
            {
                m_toFollowSent = value;
                FlagDirty();
            }
        }
        public long SPMOrderTestId
        {
            get
            {
                return m_SPMOrderTestId;
            }
            set
            {
                m_SPMOrderTestId = value;
                FlagDirty();
            }
        }

        public bool IsPresumptiveHold
        {
            get
            {
                foreach (ReportAnalyte a in m_orderAnalytes.List)
                {
                    if (!a.IsPresumptiveHold)
                        return false;
                }
                return true;
            }
        }

        [Audit("SPMStatus")]
        public SPMStatusValue SPMStatus
        {
            get
            {
                return (SPMStatusValue)m_spmStatus;
            }
            set
            {
                m_spmStatus = (int)value;
                FlagDirty();
            }
        }

        [Audit("ParentTestCode")]
        public string ParentTestCode
        {
            get
            {
                return m_parentTestCode;
            }
            set
            {
                if ((m_parentTestCode ?? "") != (value.Trim() ?? ""))
                {
                    m_parentTestCode = value.Trim();
                    FlagDirty();
                }
            }
        }

        #endregion

        #region Data Functions

        internal void Load(DataRow row)
        {

            m_id = Conversions.ToLong(row["ReportAnalytePanelID"]);
            m_panelCode = Conversions.ToString(row["PanelCode"]);
            m_transmitStatus = (transmitStatusType)Conversions.ToInteger(row["PanelTransmitStatus"]);
            m_onLoadTransmitStatus = m_transmitStatus;
            m_orderingPanelCodes.AddRange(row["OrderingPanelCode"].ToString().Split(','));
            m_criticalType = (criticalType)Conversions.ToInteger(row["PanelCriticalType"]); // aaa'
            m_releaseDate = Conversions.ToDate(row["PanelReleaseDate"]);

            if (row.Table.Columns.Contains("IsPreliminaryReleased"))
            {
                m_isPreliminaryReleased = Conversions.ToBoolean(row["IsPreliminaryReleased"]);
            }

            if (row.Table.Columns.Contains("MarkedAsPreliminary"))
            {
                m_markedAsPreliminary = Conversions.ToBoolean(row["MarkedAsPreliminary"]);
            }

            m_toFollowSent = Conversions.ToBoolean(row["PanelToFollowSent"]);
            m_SPMOrderTestId = Conversions.ToLong(row["SPMOrderTestId"]);

            m_panel = new RefAnalytePanel(this);
            m_panel.Load(row);


            // Demo Update: Read isdeleted from db and update the base class 
            m_isDeleted = Conversions.ToBoolean(Interaction.IIf(row["IsPanelDeleted"] is DBNull, false, row["IsPanelDeleted"]));

            m_spmStatus = Conversions.ToInteger(row["PanelSPMStatus"]);
            m_parentTestCode = Conversions.ToString(row["PanelParentTestCode"]);


            FlagClean();

        }

        internal void Update()
        {

            Logger.Debug($"{PanelCode} Panel Start Saving....");

            if (base.IsDirty)
            {

                var da = new DataWrapper(Configuration.ConnectionString);
                var paramList = new List<DbParameter>();

                // 'The date is reset in the update statement so that dates are consistent and do not come from the client application.
                // If m_resetReleaseDate Then m_releaseDate = DateTime.Now()

                paramList.Add((DbParameter)da.CreateParameter("@ReportAnalytePanelId", DbType.Int64, m_id, ParameterDirection.InputOutput));
                paramList.Add((DbParameter)da.CreateParameter("@ReportId", DbType.Int64, m_parent.ID));
                paramList.Add((DbParameter)da.CreateParameter("@PanelCode", DbType.String, m_panelCode));
                paramList.Add((DbParameter)da.CreateParameter("@TransmitStatus", DbType.Int32, m_transmitStatus));
                paramList.Add((DbParameter)da.CreateParameter("@OrderingPanelCode", DbType.String, string.Join(",", m_orderingPanelCodes.ToArray())));
                paramList.Add((DbParameter)da.CreateParameter("@CriticalType", DbType.Int32, m_criticalType)); // aaa'
                paramList.Add((DbParameter)da.CreateParameter("@IsPreliminaryReleased", DbType.Boolean, m_isPreliminaryReleased));
                paramList.Add((DbParameter)da.CreateParameter("@MarkedAsPreliminary", DbType.Boolean, m_markedAsPreliminary));
                paramList.Add((DbParameter)da.CreateParameter("@ResetReleaseDate", DbType.Boolean, m_resetReleaseDate));
                if (m_releaseDate > DateTime.Parse("1900-01-01"))
                    paramList.Add((DbParameter)da.CreateParameter("@ReleaseDate", DbType.DateTime, m_releaseDate));
                paramList.Add((DbParameter)da.CreateParameter("@ToFollowSent", DbType.Boolean, m_toFollowSent));
                paramList.Add((DbParameter)da.CreateParameter("@IsDeleted", DbType.Boolean, m_isDeleted));
                paramList.Add((DbParameter)da.CreateParameter("@SPMOrderTestId", DbType.Int64, m_SPMOrderTestId));
                paramList.Add((DbParameter)da.CreateParameter("@SPMStatus", DbType.Int32, m_spmStatus));
                paramList.Add((DbParameter)da.CreateParameter("@ParentTestCode", DbType.String, m_parentTestCode));

                DbParameter[] @params = paramList.ToArray();

                m_id = Conversions.ToLong(da.ExecuteNonQuery("lis_ReportAnalytePanel_Save", @params)["@ReportAnalytePanelId"].Value);

            }

            // Call this before FlagClean is called so that the ObjectLookupId can be set correctly from the RefAnalytePanel
            if (IsNew)
            {
                UpdateReferenceAnalytePanel();
                // m_panel.Update()
            }

            Analytes.Update();
            m_auditItemList.AddRange(Analytes.GetAuditItems());

            Comments.Update();
            m_auditItemList.AddRange(Comments.GetAuditItems());

            // NA 2/27/2014 : reset the original status on each panel component
            Analytes.SetOrigResultStatus();

            Logger.Debug($"{PanelCode} Panel Save Completed. Start Audit...");

            m_auditItemList.AddRange(GetAuditItemsAndClean(true));
            // Me.FlagClean(True)

            Logger.Debug($"{PanelCode} Panel Audit Completed.");

        }

        private void UpdateReferenceAnalytePanel()
        {

            Logger.Debug($"{PanelCode} Start update Ref Panel...");

            // 'This is using the old update method where the refanalyte and mapping are updated in the same proc
            if (Configuration.AppSettings.GetBool("Bioreference.LIS:AddTestFromTestMaster"))
            {

                m_panel.UpdateCombined();
            }

            else
            {

                bool mapRef = m_panel.IsNew; // If RefAnalytePanel is new (new ReportAnalytePanel) or it is updated below, we need to remap

                // The reference analyte CAN be updated, ie. sendout send update analyte values.
                if (m_panel.Id == 0L || m_panel.IsDirty)
                {
                    m_panel.UpdateCore();
                    mapRef = true;
                }

                if (mapRef) // For a new ReportAnalyte or update of RefAnalyte, need to map RefAnalyte
                {
                    m_panel.Update();
                }

            }

            Logger.Debug($"{PanelCode} Ref Panel update Complete.");

        }

        internal void Delete()
        {

            var da = new DataWrapper(Configuration.ConnectionString);
            var @param = new DbParameter[1];

            @param[0] = (DbParameter)da.CreateParameter("@ReportAnalytePanelId", DbType.Int64, m_id);

            da.ExecuteNonQuery("lis_ReportAnalytePanel_Delete", @param);

            // 'Need to call update, comments can be added on deleted Analytes:)
            Comments.Update();

            FlagDeleted();
            m_auditItemList.AddRange(GetAuditItemsAndClean());
            // Me.FlagClean()

        }

        #endregion


        public void ResetAuditItems()
        {
            m_auditItemList = new List<string>();

            foreach (ReportAnalyte rptAnalyte in m_orderAnalytes.List)
                rptAnalyte.ResetAuditItems();

            ResetAudit();
        }

        public override void FlagUnDeleted()
        {

            m_isDeleted = false;
            base.FlagUnDeleted();

        }

        public void ResetPanel()
        {
            SetTransmitStatus(transmitStatusType.None);
            SetPreliminaryReleased(false);
            RemoveAllComments();
            AuditManager.LogCustomObjectAction(this, "SPM specimen update.");
        }

        #region Compare

        public override List<CompareResult> CompareObject(object obj)
        {

            ReportAnalytePanel panel = (ReportAnalytePanel)obj;

            var list = new List<CompareResult>();

            // 'Get base compare values
            list.AddRange(base.CompareObject(obj));

            list.AddRange(CompareResult.CompareObjects(Analytes.List, panel.Analytes.List));
            list.AddRange(CompareResult.CompareObjects(Comments.List, panel.Comments.List, PanelName));

            return list;

        }

        #endregion

    }
} // ReportAnalytePanel