using System;
using System.Collections.Generic;
using Bioreference.Common.Lab;
using Bioreference.Common.TestMaster;
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '
// '  OrderAnalytePanels.vb
// '  Implementation of the Class OrderAnalytePanels
// '  Generated by Enterprise Architect
// '  Created on:      31-Jan-2008 5:23:29 PM
// '  Original author: Angelo Galeotafiore
// '  
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '  Modification history:
// '  
// '
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

using Bioreference.Data;

namespace Bioreference.LIS
{

    [Serializable()]
    public class ReportAnalytePanels : DataClassBase
    {

        private ReportAnalytePanelList m_list;
        private Report m_parent;
        private static readonly ILog Log = LogManager.GetLogger<ReportAnalytePanels>();

        internal ReportAnalytePanels(Report parent)
        {
            m_parent = parent;
            m_list = new ReportAnalytePanelList();
        }

        internal ReportAnalytePanel Add(TestAnalytePanel panel, string orderingPanelCode, SPMStatusValue spmStatus = SPMStatusValue.None)
        {
            return Add(panel, orderingPanelCode, "", "", spmStatus: spmStatus);
        }

        internal ReportAnalytePanel Add(TestAnalytePanel panel, string orderingPanelCode, string accessionFacility, string performFacility, long spmOrderTestId = 0, SPMStatusValue spmStatus = SPMStatusValue.None)
        {

            var p = new ReportAnalytePanel(m_parent, panel, orderingPanelCode, spmStatus);
            p.SetPerformingFacility(performFacility);
            p.SetAccessioningFacility(accessionFacility);
            p.SPMOrderTestId = spmOrderTestId;
            foreach (TestAnalyte c in panel.Analytes.List)
            {
                if (c.IsCalculation && !string.IsNullOrEmpty(c.Calculation.Expression))
                {
                    m_parent.m_hasCalcAnalytes = true;
                    break;
                }
            }
            m_parent.AddToTestCodeHash(p.PanelCode);
            return p;

        }

        public ReportAnalytePanel Add(TestInfo testInfo, string orderingPanelCode, SPMStatusValue spmStatus = SPMStatusValue.None)
        {
            return Add(testInfo, orderingPanelCode, "", "", spmStatus: spmStatus);
        }

        public ReportAnalytePanel Add(TestInfo testInfo, string orderingPanelCode, string accessionFacility, string performFacility, long spmOrderTestId = 0, SPMStatusValue spmStatus = SPMStatusValue.None)
        {

            var p = new ReportAnalytePanel(m_parent, testInfo, orderingPanelCode, spmStatus);
            p.SetPerformingFacility(performFacility);
            p.SetAccessioningFacility(accessionFacility);
            p.SPMOrderTestId = spmOrderTestId;

            foreach (TestInfo c in testInfo.Components)
            {
                if (c.IsCalculation)
                {
                    m_parent.m_hasCalcAnalytes = true;
                    break;
                }
            }

            m_parent.AddToTestCodeHash(p.PanelCode);
            return p;

        }

        public ReportAnalytePanel Add(string testPanelCode, string testPanelName = "", SPMStatusValue spmStatus = SPMStatusValue.None)
        {

            // Create a bogus AnalytePanel so that a RefAnalytePanel can be created from it
            var panel = new AnalytePanel();
            panel.PanelCode = testPanelCode;
            panel.Name = testPanelName;

            var r = new ReportAnalytePanel(m_parent, (TestAnalytePanel)panel, testPanelCode, spmStatus);
            // r.SetReferenceLab(referenceLabId, referenceLabCode)
            // If testPanelCode <> "" Then r.Panel.PanelCode = testPanelCode
            List.Add(r);

            return r;

        }

        /// <summary>
    /// derived from list of OrderAnalytePanel in OrderAnalytePanelList
    /// </summary>
        public resultStatusType GetStatus()
        {

            int i = 0;
            int x = 0;
            foreach (ReportAnalytePanel o in List)
            {
                x = (int)o.GetStatus();
                if (x > i)
                    i = x;
            }

            return default;

        }

        public ReportAnalytePanelList List
        {
            get
            {
                return m_list;
            }
        }

        public ReportAnalytePanel Find(int reportAnalytePanelId)
        {

            return Find(reportAnalytePanelId, false);

        }

        public ReportAnalytePanel Find(int reportAnalytePanelId, bool searchDeleted)
        {

            foreach (ReportAnalytePanel p in List)
            {
                if (p.Id == reportAnalytePanelId)
                    return p;
            }

            if (searchDeleted)
            {
                foreach (ReportAnalytePanel p in List.ArchivedDeletedList)
                {
                    if (p.Id == reportAnalytePanelId)
                        return p;
                }
            }

            return null;

        }

        public ReportAnalytePanel Find(string panelCode, string orderedCode)
        {

            foreach (ReportAnalytePanel p in List)
            {
                if ((panelCode.TrimStart(new char[] { '0' }) ?? "") == (p.PanelCode.TrimStart(new char[] { '0' }) ?? "") && p.ContainsOrderCode(orderedCode))
                    return p;
                // 'orderedCode.TrimStart(New Char() {"0"}) = p.OrderingPanelCode.TrimStart(New Char() {"0"}) 
            }
            return null;

        }

        public ReportAnalytePanel Find(string panelCode, int referenceLabId = 0)
        {

            if (referenceLabId == 0)
            {
                foreach (ReportAnalytePanel p in List)
                {
                    if ((panelCode.TrimStart(new char[] { '0' }) ?? "") == (p.PanelCode.TrimStart(new char[] { '0' }) ?? ""))
                        return p;

                    // AG 12/8/2008 - Check for Ordering testCode.
                    // If panelCode.TrimStart(New Char() {"0"}) = p.OrderingPanelCode.TrimStart(New Char() {"0"}) Then Return p
                }
            }
            else
            {
                foreach (ReportAnalytePanel p in List)
                {
                    if (p.Panel.ReferenceLabId == referenceLabId)
                    {
                        // AG 12/8/2008 - Check for Ordering testCode.
                        if ((p.Panel.ReferenceLabCode.TrimStart(new char[] { '0' }) ?? "") == (panelCode.TrimStart(new char[] { '0' }) ?? ""))
                            return p;
                        // 'OrElse p.OrderingPanelCode.TrimStart(New Char() {"0"}) = panelCode.TrimStart(New Char() {"0"}) 

                        // 'ReferenceLab Ordering Code.
                        if (ReferenceEquals(p.Panel.GetType(), typeof(RefAnalytePanel)))
                        {
                            if ((((RefAnalytePanel)p.Panel).RefLabOrderingCode.TrimStart(new char[] { '0' }) ?? "") == (panelCode.TrimStart(new char[] { '0' }) ?? ""))
                                return p;
                        }
                    }
                }
            }
            return null;

        }

        /// 
    /// <param name="orderPanelId"></param>
        public void Remove(int orderPanelId)
        {

            foreach (ReportAnalytePanel p in List)
            {
                if (p.Id == orderPanelId)
                {

                    List.Remove(p);
                    // m_parent.SendAccessionStatusToReporting()
                    m_parent.CheckAndFlagIfResend();
                    break;
                }
            }

        }

        /// 
    /// <param name="orderPanel"></param>
        public void Remove(ReportAnalytePanel orderPanel)
        {

            List.Remove(orderPanel);
            // m_parent.SendAccessionStatusToReporting()
            m_parent.CheckAndFlagIfResend();

        }

        internal void Update()
        {

            m_list.Update();

            // 'Update deleted panels.  Could have added demo update comment after deleted.
            foreach (ReportAnalytePanel p in m_list.ArchivedDeletedList)
            {
                if (p.IsDirty)
                    p.Update();
            }

        }

        public List<string> GetAuditItems()
        {
            var lst = new List<string>();

            foreach (ReportAnalytePanel c in m_list)
                lst.AddRange(c.GetFormattedAuditItems);

            foreach (ReportAnalytePanel c in m_list.ArchivedDeletedList)
                lst.AddRange(c.GetFormattedAuditItems);

            return lst;

        }

        public override bool IsDirty
        {
            get
            {
                if (m_list.IsDirty)
                    return true;

                // 'Archived panels can be updated!
                foreach (ReportAnalytePanel p in m_list.ArchivedDeletedList)
                {
                    if (p.IsDirty)
                        return true;
                }
                return false;

            }
        }


        public void ResetAudit()
        {
            foreach (ReportAnalytePanel c in m_list)
                c.ResetAuditItems();
        }

    }
} // OrderAnalytePanels