using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using Bioreference.Common.TestMaster;
using Bioreference.Data;
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '
// '  ReportComment.vb
// '  Implementation of the Class ReportComment
// '  Generated by Enterprise Architect
// '  Created on:      31-Jan-2008 2:24:23 PM
// '  Original author: Angelo Galeotafiore
// '  
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '  Modification history:
// '  
// '
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
using Bioreference.Data.Audit;
using Bioreference.Data.Client;
using Bioreference.LIS.Helper;
using Microsoft.VisualBasic.CompilerServices;

namespace Bioreference.LIS
{

    [Serializable()]
    public class ReportComment : AuditDataClassBase
    {

        private DataClassBase m_parent = null;
        private DateTime m_dateCreated = DateTime.Parse("1900-01-01");
        private long m_id = 0L;
        private string m_text = "";
        private string m_externalId = "";
        private bool m_isAutoAdded = false;
        private CommentType m_commentType;
        private string m_externalCommentCode = "";
        private int m_internalNoteId = -1;
        private string m_internalNoteText = "";
        private int m_priority = 0;

        private ExternalCommentType m_externalCommentType = ExternalCommentType.Comment;

        private List<string> m_auditItemList;

        internal ReportComment(DataClassBase parent, bool loadAudit = false)
        {
            m_parent = parent;
            m_auditItemList = new List<string>();
            LoadAudit = loadAudit;
            FlagChild();
        }

        internal ReportComment(DataClassBase parent, string externalId, bool isAutoAdded, string extCommentCode, ExternalCommentType extCommentType, int priority)
        {
            m_auditItemList = new List<string>();
            m_parent = parent;
            m_externalId = externalId;
            m_isAutoAdded = isAutoAdded;
            m_externalCommentCode = extCommentCode;
            m_externalCommentType = extCommentType;
            m_priority = priority;
            FlagChild();

            // LoadAuditFromObject() 'Call this to force an audit of the audit text everytime.
        }

        #region Public Properties

        /// <summary>
    /// Parent object can be Report,ReportAnalytePanel, or ReportAnalyte
    /// </summary>
    /// <value></value>
    /// <returns></returns>
    /// <remarks></remarks>
        public DataClassBase Parent
        {
            get
            {
                return m_parent;
            }
        }

        public CommentType CommentType
        {
            get
            {
                return m_commentType;
            }
        }

        public bool IsAutoAdded
        {
            get
            {
                return m_isAutoAdded;
            }
        }

        [Audit("Text", true)]
        public string Text
        {
            get
            {
                return m_text;
            }
            set
            {
                if ((value.TrimEnd() ?? "") != (m_text ?? ""))
                {
                    m_text = value.TrimEnd().NormalizeToWindows();

                    if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalyte)))
                    {
                        ReportAnalyte a = (ReportAnalyte)m_parent;
                        if (a.HasBeenReleased() && a.IsPreviousStatusNotReleased())
                            a.ResultStatus = resultStatusType.Corrected;
                    }

                    FlagDirty();
                }
            }
        }

        public DateTime DateCreated
        {
            get
            {
                return m_dateCreated;
            }
        }

        public long ID
        {
            get
            {
                return m_id;
            }
        }

        public override object IdentifierId
        {
            get
            {
                return m_id;
            }
        }

        protected override object ParentIdentifierId
        {
            get
            {
                if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalyte)))
                {
                    return ((ReportAnalyte)m_parent).GetParentReport().AccessionIdentifier;
                }
                else if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalytePanel)))
                {
                    return ((ReportAnalytePanel)m_parent).Parent.AccessionIdentifier;
                }
                else if (ReferenceEquals(m_parent.GetType(), typeof(Report)))
                {
                    return ((Report)m_parent).AccessionIdentifier;
                }
                else
                {
                    return 0;
                }
            }
        }

        protected override long ObjectLookupIdentifier
        {
            get
            {
                if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalyte)))
                {
                    return ((RefAnalyte)((ReportAnalyte)m_parent).Analyte).Id;
                }
                else if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalytePanel)))
                {
                    return ((RefAnalytePanel)((ReportAnalytePanel)m_parent).Panel).Id;
                }
                else
                {
                    return 0L;
                }
            }
        }

        protected override int ObjectLookupType
        {
            get
            {
                if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalyte)))
                {
                    return 3;
                }
                else if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalytePanel)))
                {
                    return 2;
                }
                else
                {
                    return 1;
                } // Report
            }
        }


        /// <summary>
    /// ID that is from an external app, such as Vertex. This is for reference purposes only.
    /// </summary>
    /// <value></value>
    /// <returns></returns>
    /// <remarks></remarks>
        public string ExternalId
        {
            get
            {
                return m_externalId;
            }
        }

        public ExternalCommentType ExternalCommentType
        {
            get
            {
                return m_externalCommentType;
            }
        }

        public string ExternalCommentCode
        {
            get
            {
                return m_externalCommentCode;
            }
        }

        [Audit("Priority", true)]
        public int Priority
        {
            get
            {
                return m_priority;
            }
            set
            {
                if (value != m_priority)
                {
                    m_priority = value;
                    FlagDirty();
                }
            }
        }

        public List<string> GetFormattedAuditItems
        {
            // get the audit item of this object as well as any object in the Save stream.
            get
            {
                return m_auditItemList;
            }
        }

        public int InternalNoteId
        {
            get
            {
                return m_internalNoteId;
            }
            set
            {
                m_internalNoteId = value;
                FlagDirty();
            }
        }

        [Audit("InternalNote", true)]
        public string InternalNote
        {
            get
            {
                return m_internalNoteText;
            }
            set
            {
                m_internalNoteText = value.NormalizeToWindows();
            }
        }
        #endregion

        #region Data Functions

        internal void Update()
        {

            long parentId = 0L;
            var parentType = orderParentType.Unknown;

            if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalyte)))
            {
                parentType = orderParentType.ReportAnalyte;
                parentId = ((ReportAnalyte)m_parent).ID;
            }
            else if (ReferenceEquals(m_parent.GetType(), typeof(ReportAnalytePanel)))
            {
                parentType = orderParentType.ReportAnalytePanel;
                parentId = ((ReportAnalytePanel)m_parent).Id;
            }
            else if (ReferenceEquals(m_parent.GetType(), typeof(Report)))
            {
                parentType = orderParentType.Report;
                parentId = ((Report)m_parent).ID;
            }

            if (!string.IsNullOrEmpty(m_externalId))
            {

                Report report = null;
                if (parentType == orderParentType.Report)
                {
                    report = (Report)m_parent;
                }
                else if (parentType == orderParentType.ReportAnalytePanel)
                {
                    report = ((ReportAnalytePanel)m_parent).Parent;
                }
                else if (parentType == orderParentType.ReportAnalyte)
                {
                    ReportAnalyte analyte = (ReportAnalyte)m_parent;
                    if (ReferenceEquals(analyte.Parent.GetType(), typeof(Report)))
                    {
                        report = (Report)analyte.Parent;
                    }
                    else
                    {
                        report = ((ReportAnalytePanel)analyte.Parent).Parent;
                    }
                }

                if (report.FindCommentGroup(m_externalId) == null)
                {
                    report.m_reportCommentGroups.Add(new ReportCommentGroup(report, m_externalId, report.FindCommentGroupNextPosition()));
                }

            }

            var da = new DataWrapper(Configuration.ConnectionString);
            var paramList = new List<DbParameter>();

            paramList.Add((DbParameter)da.CreateParameter("@ReportCommentId", DbType.Int64, m_id, ParameterDirection.InputOutput));
            paramList.Add((DbParameter)da.CreateParameter("@ParentType", DbType.Int32, parentType));
            paramList.Add((DbParameter)da.CreateParameter("@ParentId", DbType.Int64, parentId));
            paramList.Add((DbParameter)da.CreateParameter("@Text", DbType.String, m_text));
            // AG - Comments
            paramList.Add((DbParameter)da.CreateParameter("@ExternalId", DbType.String, m_externalId));
            paramList.Add((DbParameter)da.CreateParameter("@IsAutoAdded", DbType.Boolean, m_isAutoAdded));
            paramList.Add((DbParameter)da.CreateParameter("@ExtCommentCode", DbType.String, m_externalCommentCode));
            paramList.Add((DbParameter)da.CreateParameter("@ExtCommentType", DbType.Int32, m_externalCommentType));
            paramList.Add((DbParameter)da.CreateParameter("@Priority", DbType.Int32, m_priority));

            DbParameter[] @params = paramList.ToArray();

            m_id = Conversions.ToLong(da.ExecuteNonQuery("lis_ReportComment_Save", @params)["@ReportCommentId"].Value);

            // NA: Get the list of AuditItem in this object after issuing the Clean so all properties are correctly populated.
            m_auditItemList.AddRange(GetAuditItemsAndClean(true));
            // Me.FlagClean(True)
            if (m_internalNoteId > -1)
            {
                SaveInternalNote(parentId, (int)parentType);
            }

        }

        private void SaveInternalNote(long parentId, int parentType)
        {

            var da = new DataWrapper(Configuration.ConnectionString);
            var paramList = new List<DbParameter>();

            paramList.Add((DbParameter)da.CreateParameter("@ReportCommentId", DbType.Int64, m_id));
            paramList.Add((DbParameter)da.CreateParameter("@ParentType", DbType.Int32, parentType));
            paramList.Add((DbParameter)da.CreateParameter("@ParentId", DbType.Int64, parentId));
            paramList.Add((DbParameter)da.CreateParameter("@InternalNoteID", DbType.String, m_internalNoteId));
            paramList.Add((DbParameter)da.CreateParameter("@InternalNoteText", DbType.String, m_internalNoteText));
            if (!(CurrentUser == null))
            {
                paramList.Add((DbParameter)da.CreateParameter("@CreatedBy", DbType.String, CurrentUser.Name));
            }
            else
            {
                paramList.Add((DbParameter)da.CreateParameter("@CreatedBy", DbType.String, ""));
            }
            DbParameter[] @params = paramList.ToArray();

            da.ExecuteNonQuery("lis_InternalNote_Save", @params);

        }

        internal void Delete()
        {

            var da = new DataWrapper(Configuration.ConnectionString);
            var @param = new DbParameter[1];

            @param[0] = (DbParameter)da.CreateParameter("@ReportCommentId", DbType.Int64, m_id);

            da.ExecuteNonQuery("lis_ReportComment_Delete", @param);

            FlagDeleted();
            // NA: Get the list of AuditItem in this object after issuing the Clean so all properties are correctly populated.
            m_auditItemList.AddRange(GetAuditItemsAndClean());
            // Me.FlagClean()

        }

        internal void Load(DataRow row)
        {

            m_dateCreated = Conversions.ToDate(row["DateCreated"]);
            m_id = Conversions.ToLong(row["ReportCommentId"]);
            m_text = Conversions.ToString(row["CommentText"]).NormalizeToWindows();
            // AG - Comments
            m_externalId = Conversions.ToString(row["ExternalId"]);
            m_isAutoAdded = Conversions.ToBoolean(row["IsAutoAdded"]);
            m_externalCommentCode = Conversions.ToString(row["ExtCommentCode"]);
            m_externalCommentType = (ExternalCommentType)Conversions.ToInteger(row["ExtCommentType"]);
            m_priority = Conversions.ToInteger(row["Priority"]);

            FlagClean();

        }


        public void ResetAuditItems()
        {
            m_auditItemList = new List<string>();
            ResetAudit();
        }

        public void SetCommentType(CommentType commentType)
        {
            m_commentType = commentType;
        }

        #endregion

        #region Compare

        public override string CompareObjectDiplayName
        {
            get
            {
                return Text;
            }
        }

        #endregion

    }
} // OrderComment