using System;
using System.Collections.Generic;
using System.Data;
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '
// '  OrderAnalyteList.vb
// '  Implementation of the Class OrderAnalyteList
// '  Generated by Enterprise Architect
// '  Created on:      31-Jan-2008 2:53:36 PM
// '  Original author: Angelo Galeotafiore
// '  
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '  Modification history:
// '  
// '
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

using System.Data.SqlClient;
using System.Diagnostics;
using Bioreference.Data;
using Microsoft.VisualBasic.CompilerServices;

namespace Bioreference.LIS
{

    [Serializable()]
    public class ReportAnalyteList : DataClassCollectionBase
    {

        private readonly ILog Log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private Dictionary<string, ReportAnalyte> updatedList = new Dictionary<string, ReportAnalyte>();
        private Dictionary<string, RefAnalyte> updatedRefAnalyteList = new Dictionary<string, RefAnalyte>();


        internal void Add(ReportAnalyte analyte)
        {
            List.Add(analyte);
        }

        /// <summary>
    /// derived from list of OrderAnalyte
    /// </summary>
        public override bool IsDirty
        {
            get
            {
                if (!(DeletedItemsList == null) && DeletedItemsList.Count > 0)
                    return true;

                foreach (ReportAnalyte o in List)
                {
                    if (o.IsDirty)
                        return true;
                }

                return false;

            }
        }

        /// 
    /// <param name="index"></param>
        public ReportAnalyte this[int index]
        {
            get
            {
                return (ReportAnalyte)List[index];
            }
        }

        /// 
    /// <param name="analyte"></param>
        public void Remove(ReportAnalyte analyte)
        {
            List.Remove(analyte);
        }

        internal void Update()
        {

            if (Configuration.LISSettings.GetBool("ReportAnalyteBatching"))
            {
                Update_WithBatching();
            }
            else
            {
                Update_WithoutBatching();
            }


        }

        internal void Update_WithBatching()
        {

            var reportAnalyteTable = CreateReportAnalyteDataTable();
            var refAnalyteTable = CreateRefAnalyteDataTable();
            DataRow reportAnalyteRow, refAnalyteRow;
            var timer = new Stopwatch();
            timer.Start();
            foreach (ReportAnalyte a in List)
            {
                if (a.IsDirty)
                {
                    if (!updatedList.ContainsKey(a.Code))
                    {
                        updatedList.Add(a.Code, a);
                    }
                    reportAnalyteRow = reportAnalyteTable.NewRow();
                    a.GetUpdateRow(ref reportAnalyteRow);
                    reportAnalyteTable.Rows.Add(reportAnalyteRow);
                }
            }

            var dtOut = SaveReportAnalyteBatch(reportAnalyteTable);
            SetReportAnalyteId(dtOut);
            foreach (ReportAnalyte a in List)
            {
                if (a.IsDirty)
                {
                    if (!updatedRefAnalyteList.ContainsKey(a.Code))
                    {
                        updatedRefAnalyteList.Add(a.Code, (RefAnalyte)a.Analyte);
                    }
                    refAnalyteRow = refAnalyteTable.NewRow();
                    a.Update(ref refAnalyteRow);
                    if (refAnalyteRow is not null)
                    {
                        refAnalyteTable.Rows.Add(refAnalyteRow);
                    }
                }
            }

            var dtRefOut = SaveRefAnalyteBatch(refAnalyteTable);
            SetRefAnalyteId(dtRefOut);

            timer.Stop();
            object elapsedTime = timer.ElapsedMilliseconds;

            Log.DebugFormat("Call for batch Save ReportAnalyte took {0} milliseconds", elapsedTime);

            if (!(DeletedItemsList == null))
            {
                foreach (ReportAnalyte a in DeletedItemsList)
                {
                    if (a.IsNew == false)
                        a.Delete();
                }
                DeletedItemsList.Clear();
            }


        }
        internal void Update_WithoutBatching()
        {
            var timer = new Stopwatch();
            timer.Start();
            foreach (ReportAnalyte a in List)
            {
                if (a.IsDirty)
                {
                    a.Update();
                }
            }
            timer.Stop();
            object elapsedTime = timer.ElapsedMilliseconds;
            Log.DebugFormat("Total Time for Save ReportAnalyte without batch took {0} milliseconds", elapsedTime);

            if (!(DeletedItemsList == null))
            {
                foreach (ReportAnalyte a in DeletedItemsList)
                {
                    if (a.IsNew == false)
                        a.Delete();
                }
                DeletedItemsList.Clear();
            }

        }

        private void SetRefAnalyteId(DataTable dtRefOut)
        {
            if (dtRefOut is null || dtRefOut.Rows.Count == 0)
            {
                return;
            }
            foreach (DataRow dr in dtRefOut.Rows)
            {
                if (updatedRefAnalyteList.ContainsKey(Conversions.ToString(dr[1])))
                {
                    updatedRefAnalyteList[Conversions.ToString(dr[1])].SetRefAnalyteId(Conversions.ToLong(dr[0]));
                }
            }
        }

        private DataTable SaveRefAnalyteBatch(DataTable refAnalyteTable)
        {

            if (refAnalyteTable is null || refAnalyteTable.Rows.Count == 0)
            {
                return null;
            }
            var conn = new SqlConnection(Configuration.ConnectionString);
            SqlCommand cmd = null;
            var dtOut = new DataTable();
            SqlDataAdapter da;
            try
            {

                cmd = new SqlCommand();
                cmd.Connection = conn;
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "lis_RefAnalyte_Batch_Save";

                cmd.Parameters.AddWithValue("@RefAnalyteTableType", SqlDbType.Structured).Value = refAnalyteTable;

                da = new SqlDataAdapter(cmd);
                da.Fill(dtOut);

                return dtOut;
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        private DataTable CreateRefAnalyteDataTable()
        {
            var table = new DataTable();
            {
                var withBlock = table.Columns;
                withBlock.Add("RefAnalyteId", typeof(long));
                withBlock.Add("ReportAnalyteId", typeof(long));
                withBlock.Add("Code", typeof(string));
                withBlock.Add("FlagValue", typeof(string));
                withBlock.Add("Name", typeof(string));
                withBlock.Add("RefRange", typeof(string));
                withBlock.Add("Units", typeof(string));
                withBlock.Add("Category", typeof(string));
                withBlock.Add("CommentsXml", typeof(string));
                withBlock.Add("CriticalsXml", typeof(string));
                withBlock.Add("ResultValuesXml", typeof(string));
                withBlock.Add("ResultType", typeof(int));
                withBlock.Add("ReferenceLabID", typeof(int));
                withBlock.Add("ReferenceLabAnalyteCode", typeof(string));
                withBlock.Add("FlagRangesXml", typeof(string));
                withBlock.Add("DisplayByDefault", typeof(bool));
                withBlock.Add("IsReportable", typeof(bool));
                withBlock.Add("TestCodeMappingsXml", typeof(string));
                withBlock.Add("OutboundChannelId", typeof(int));
                withBlock.Add("Calculation", typeof(string));
                withBlock.Add("AllowUpdates", typeof(bool));
                withBlock.Add("IsAgencyReportable", typeof(bool));
                withBlock.Add("ReportingType", typeof(int));
                withBlock.Add("AttachCommentToParent", typeof(bool));
                withBlock.Add("AutoRelease", typeof(bool));
                withBlock.Add("Precision", typeof(int));
                withBlock.Add("ReferenceLabOrderingCode", typeof(string));
                withBlock.Add("AltInboundTestCode", typeof(string));
                withBlock.Add("AltOutboundTestCode", typeof(string));
                withBlock.Add("AltOutboundTestDesc", typeof(string));
                withBlock.Add("PreviousRefRange", typeof(string));
                withBlock.Add("PreviousUnits", typeof(string));
                withBlock.Add("PreviousFlag", typeof(string));
                withBlock.Add("IsFlagDeleted", typeof(bool));
                withBlock.Add("AllowPreliminaryRelease", typeof(bool));
                withBlock.Add("AllowInternalRefRanges", typeof(bool));
                withBlock.Add("IsPOC", typeof(bool));
                withBlock.Add("IsDoubleEntry", typeof(bool));
            }
            return table;
        }

        private void SetReportAnalyteId(DataTable dtOut)
        {
            if (dtOut is null || dtOut.Rows.Count == 0)
            {
                return;
            }
            foreach (DataRow dr in dtOut.Rows)
            {
                if (updatedList.ContainsKey(Conversions.ToString(dr[1])))
                {
                    updatedList[Conversions.ToString(dr[1])].SetReportAnalyteId(Conversions.ToLong(dr[0]));
                }
            }
        }

        public DataTable SaveReportAnalyteBatch(DataTable dt)
        {

            if (dt is null || dt.Rows.Count == 0)
            {
                return null;
            }

            var conn = new SqlConnection(Configuration.ConnectionString);
            SqlCommand cmd = null;
            var dtOut = new DataTable();
            SqlDataAdapter da;
            try
            {

                cmd = new SqlCommand();
                cmd.Connection = conn;
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "lis_ReportAnalyte_Batch_Save";

                cmd.Parameters.AddWithValue("@ReportAnalyteTableType", SqlDbType.Structured).Value = dt;

                da = new SqlDataAdapter(cmd);
                da.Fill(dtOut);

                return dtOut;
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        private DataTable CreateReportAnalyteDataTable()
        {
            var table = new DataTable();
            {
                var withBlock = table.Columns;
                withBlock.Add("ReportAnalyteId", typeof(long));
                withBlock.Add("ParentType", typeof(int));
                withBlock.Add("ParentId", typeof(long));
                withBlock.Add("ResultValue", typeof(string));
                withBlock.Add("TransmitStatus", typeof(int));
                withBlock.Add("ResultStatus", typeof(int));
                withBlock.Add("AnalyteCode", typeof(string));
                withBlock.Add("ResultDate", typeof(DateTime));
                withBlock.Add("FlagValue", typeof(string));
                withBlock.Add("PreviousValue", typeof(string));
                withBlock.Add("Instrument", typeof(string));
                withBlock.Add("InstrumentId", typeof(string));
                withBlock.Add("InstrumentAlt1", typeof(string));
                withBlock.Add("InstrumentAlt2", typeof(string));
                withBlock.Add("InstrumentAlt3", typeof(string));
                withBlock.Add("SpecimenRackId", typeof(string));
                withBlock.Add("SpecimenRackPosition", typeof(string));
                withBlock.Add("SpecimenRackSequence", typeof(string));
                withBlock.Add("SpecimenAlt1", typeof(string));
                withBlock.Add("SpecimenAlt2", typeof(string));
                withBlock.Add("OrderingAnalyteCode", typeof(string));
                withBlock.Add("CriticalType", typeof(int)); // aaa'
                withBlock.Add("ReleaseDate", typeof(DateTime));
                withBlock.Add("IsResultManual", typeof(bool));
                withBlock.Add("ResultAnalyzedTechUser", typeof(string));
                withBlock.Add("ResultReleasedUser", typeof(string));
                withBlock.Add("PerformingFacility", typeof(string));
                withBlock.Add("AccessioningFacility", typeof(string));
                withBlock.Add("IsDeleted", typeof(bool));
                withBlock.Add("ReleasedValue", typeof(string));
                withBlock.Add("ReleasedStatus", typeof(int));
                withBlock.Add("PriorReleaseValue", typeof(string));
                withBlock.Add("PriorReleaseDate", typeof(DateTime));
                withBlock.Add("UserName", typeof(string));
                withBlock.Add("IsCOCReviewed", typeof(bool));
                withBlock.Add("COCApprover", typeof(string));
                withBlock.Add("COCApprovedDate", typeof(DateTime));
                withBlock.Add("ResetReleaseDate", typeof(bool));
                withBlock.Add("ToFollowSent", typeof(bool));
                withBlock.Add("CodeTypeId", typeof(int));
                withBlock.Add("IsPreliminaryReleased", typeof(bool));
                withBlock.Add("PriorEUIDResultValue", typeof(string));
                withBlock.Add("SPMOrderTestId", typeof(long));
                withBlock.Add("IsCopiedAnalyte", typeof(bool));
                withBlock.Add("IsTestHold", typeof(bool));
                withBlock.Add("IsReportingHold", typeof(bool));
                withBlock.Add("CorrectedResultReason", typeof(string));
                withBlock.Add("PreviousFlagValue", typeof(string));
                withBlock.Add("IsPresumptiveHold", typeof(bool));
            }
            return table;
        }

        internal void SetOrigResultStatus()
        {
            foreach (ReportAnalyte a in List)
                a.SetOrigResultStatus();
        }

        /// <summary>
    /// Quick fix for audit display, should be built from base class.
    /// Allow loading of deleted list so that we can get audit info.
    /// </summary>
    /// <param name="analyte"></param>
    /// <remarks></remarks>
        internal void AddToArchiveDeletedList(ReportAnalyte analyte)
        {

            ArchivedDeletedList.Add(analyte);

        }

        // Public ReadOnly Property DeletedAnalytes() As ReportAnalyte()
        // Get
        // Dim list As List(Of ReportAnalyte) = New List(Of ReportAnalyte)
        // If Not IsNothing(Me.ArchivedDeletedList) Then
        // For Each o As Object In Me.DeletedItemsList
        // list.Add(o)
        // Next
        // End If
        // Return list.ToArray()
        // End Get
        // End Property

        public bool UnDeleteAnalyte(long analyteId)
        {

            foreach (ReportAnalyte a in ArchivedDeletedList)
            {
                if (a.ID == analyteId)
                {
                    return UnDeleteAnalyte(a);
                }
            }

            return default;

        }

        internal bool UnDeleteAnalyte(ReportAnalyte analyte)
        {

            // Check to see that the analyte doesn't already exist in active list.
            foreach (ReportAnalyte a in List)
            {
                // If a.ID = analyte.ID Then Return False
                if ((a.Code ?? "") == (analyte.Code ?? ""))
                    return false;
            }

            // Me.DeletedItemsList.Remove(analyte)
            analyte.FlagUnDeleted();
            List.Add(analyte);
            // Me.DeletedItemsList.Remove(analyte)
            return true;


        }

        public ReportAnalyte FindFirstDeleted(object analyteCode)
        {
            foreach (object o in ArchivedDeletedList)
            {
                if (Conversions.ToBoolean(Operators.ConditionalCompareObjectEqual(((ReportAnalyte)o).Code, analyteCode, false)))
                    return (ReportAnalyte)o;
            }
            return null;
        }


    }
}