using System;
using System.Collections.Generic;
using Bioreference.Common.Lab;
using Bioreference.Common.TestMaster;
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '
// '  OrderAnalytes.vb
// '  Implementation of the Class OrderAnalytes
// '  Generated by Enterprise Architect
// '  Created on:      31-Jan-2008 3:19:32 PM
// '  Original author: Angelo Galeotafiore
// '  
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '  Modification history:
// '  
// '
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

using Bioreference.Data;

namespace Bioreference.LIS
{

    [Serializable()]
    public class ReportAnalytes : DataClassBase
    {

        #region Private Members

        private DataClassBase m_parent = null;
        private ReportAnalyteList m_list = null;
        private static readonly ILog Log = LogManager.GetLogger<ReportAnalytes>();

        #endregion

        #region Constructor

        internal ReportAnalytes(DataClassBase parent)
        {
            m_parent = parent;
            m_list = new ReportAnalyteList();
        }

        #endregion

        // <Obsolete("Should be removed once TestMaster integration is complete.")> _
        // Public Function Add(ByVal analyte As Analyte, ByVal orderingAnalyteCode As String) As ReportAnalyte

        // Dim oa As ReportAnalyte = New ReportAnalyte(m_parent, analyte, orderingAnalyteCode)
        // Me.List.Add(oa)
        // Return oa

        // End Function



        internal ReportAnalyte Add(TestAnalyte analyte, string orderingAnalyteCode, SPMStatusValue spmStatus = SPMStatusValue.None)
        {
            return Add(analyte, orderingAnalyteCode, "", "", spmStatus: spmStatus);
        }

        internal ReportAnalyte Add(TestAnalyte analyte, string orderingAnalyteCode, string accessionFacility, string performFacility, long spmOrderTestId = 0, SPMStatusValue spmStatus = SPMStatusValue.None)
        {

            var oa = new ReportAnalyte(m_parent, analyte, orderingAnalyteCode, spmStatus: spmStatus);
            oa.SetPerformingFacility(performFacility);
            oa.SetAccessioningFacility(accessionFacility);
            oa.SetSPMOrderTestId(spmOrderTestId);
            Log.Debug($"Adding analyte code={oa.Code} spmStatus={oa.SPMStatus}");

            if (ReferenceEquals(m_parent.GetType(), typeof(Report)) && analyte.IsCalculation)
                ((Report)m_parent).m_hasCalcAnalytes = true;
            List.Add(oa);

            if (ReferenceEquals(m_parent.GetType(), typeof(Report)))
            {
                ((Report)m_parent).AddToTestCodeHash(orderingAnalyteCode);
                Log.Debug("Calling EvaluateRulesEx with RuleSetRelease (68)");
                ((Report)m_parent).EvaluateRulesEx(oa, "", Configuration.RuleSetRelease);
            }

            return oa;

        }

        public ReportAnalyte Add(TestInfo testInfo, string orderingAnalyteCode, SPMStatusValue spmStatus = SPMStatusValue.None)
        {
            return Add(testInfo, orderingAnalyteCode, "", "", spmStatus: spmStatus);
        }

        public ReportAnalyte Add(TestInfo testInfo, string orderingAnalyteCode, string accessionFacility, string performFacility, long spmOrderTestId = 0, SPMStatusValue spmStatus = SPMStatusValue.None)
        {

            var oa = new ReportAnalyte(m_parent, testInfo, orderingAnalyteCode, spmStatus: spmStatus);
            oa.SetPerformingFacility(performFacility);
            oa.SetAccessioningFacility(accessionFacility);
            oa.SetSPMOrderTestId(spmOrderTestId);

            if (ReferenceEquals(m_parent.GetType(), typeof(Report)) && testInfo.IsCalculation)
                ((Report)m_parent).m_hasCalcAnalytes = true;
            List.Add(oa);

            if (ReferenceEquals(m_parent.GetType(), typeof(Report)))
            {
                ((Report)m_parent).AddToTestCodeHash(orderingAnalyteCode);
                Log.Debug("Calling EvaluateRulesEx with RuleSetRelease (92)");
                ((Report)m_parent).EvaluateRulesEx(oa, "", Configuration.RuleSetRelease);
            }

            return oa;

        }

        // Used on Load of OrderAnalytes

        internal void Add(ReportAnalyte orderAnalyte)
        {
            List.Add(orderAnalyte);
        }

        // Public Function Add(ByVal referenceLabId As Integer, ByVal referenceLabCode As String, Optional ByVal testCode As String = "") As ReportAnalyte

        // Dim r As ReportAnalyte = New ReportAnalyte(m_parent)
        // If testCode <> "" Then r.Analyte.Code = testCode
        // r.SetReferenceLab(referenceLabId, referenceLabCode)
        // Me.List.Add(r)

        // Return r

        // End Function

        /// <summary>
    /// derived from ReportAnalytes in ReportAnalyteList
    /// </summary>
        public resultStatusType GetStatus()
        {
            int i = 0;
            int x = 0;
            foreach (ReportAnalyte o in List)
            {
                x = (int)o.ResultStatus;
                if (x > i)
                    i = x;
            }

            return default;
        }

        public ReportAnalyteList List
        {
            get
            {
                return m_list;
            }
        }

        /// 
    /// <param name="analyteID"></param>
        public void Remove(long analyteID)
        {
            foreach (ReportAnalyte a in m_list)
            {
                if (a.ID == analyteID)
                {
                    m_list.Remove(a);

                    if (ReferenceEquals(m_parent.GetType(), typeof(Report)))
                    {
                        // CType(m_parent, Report).SendAccessionStatusToReporting()
                        ((Report)m_parent).CheckAndFlagIfResend();
                    }

                    break;
                }
            }
        }

        /// 
    /// <param name="analyte"></param>
        public void Remove(ReportAnalyte analyte)
        {
            m_list.Remove(analyte);
            if (ReferenceEquals(m_parent.GetType(), typeof(Report)))
            {
                // CType(m_parent, Report).SendAccessionStatusToReporting()
                ((Report)m_parent).CheckAndFlagIfResend();
            }
        }

        public ReportAnalyte Find(long orderAnalyteId)
        {
            return Find(orderAnalyteId, false);
        }

        public ReportAnalyte Find(long orderAnalyteId, bool searchDeleted)
        {
            foreach (ReportAnalyte a in List)
            {
                if (a.ID == orderAnalyteId)
                    return a;
            }

            if (searchDeleted)
            {
                foreach (ReportAnalyte a in List.ArchivedDeletedList)
                {
                    if (a.ID == orderAnalyteId)
                        return a;
                }
            }
            return null;
        }

        public ReportAnalyte FindFirst(string analyteCode, int referenceLabId = 0, transmitStatusType transmitStatus = transmitStatusType.NotSet)
        {
            if (referenceLabId != 0)
            {
                foreach (ReportAnalyte a in List)
                {
                    if (transmitStatus == transmitStatusType.NotSet || a.TransmitStatus == transmitStatus)
                    {
                        // AG 12/8/2008 - Check for Ordering testCode.
                        // If a.Analyte.ReferenceLabeAnalyteCode = analyteCode AndAlso a.Analyte.ReferenceLabId = referenceLabId Then Return a
                        if (a.Analyte.ReferenceLabId == referenceLabId)
                        {
                            if (string.Equals(NormalizeAnalyteCode(a.Analyte.ReferenceLabeAnalyteCode), NormalizeAnalyteCode(analyteCode), StringComparison.OrdinalIgnoreCase))
                            {
                                return a;
                            }

                            // AG 5/27/09 - Added this because the channel pads testcodes less than 4 char long with zeroes.
                            if (string.Equals(NormalizeAnalyteCode(a.Analyte.ReferenceLabeAnalyteCode.PadLeft(4, '0')), NormalizeAnalyteCode(analyteCode.PadLeft(4, '0')), StringComparison.OrdinalIgnoreCase))
                            {
                                return a;
                            }

                            // Search by the reflab ordering code
                            if (ReferenceEquals(a.Analyte.GetType(), typeof(RefAnalyte)))
                            {
                                if (string.Equals(NormalizeAnalyteCode(((RefAnalyte)a.Analyte).ReferenceLabOrderingAnalyteCode.PadLeft(4, '0')), NormalizeAnalyteCode(analyteCode.PadLeft(4, '0')), StringComparison.OrdinalIgnoreCase))
                                {
                                    return a;
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                foreach (ReportAnalyte a in List)
                {
                    if (transmitStatus == transmitStatusType.NotSet || a.TransmitStatus == transmitStatus)
                    {
                        if (string.Equals(NormalizeAnalyteCode(a.Analyte.Code), NormalizeAnalyteCode(analyteCode), StringComparison.OrdinalIgnoreCase))
                        {
                            return a;
                        }

                        // AG 12/8/2008 - Check for Ordering testCode.
                        // If a.OrderingAnalyteCode.TrimStart(New Char() {"0"}) = analyteCode.TrimStart(New Char() {"0"}) Then Return a
                    }
                }

                // Now search aliases aka testcodemapping
                foreach (ReportAnalyte a in List)
                {
                    if (transmitStatus == transmitStatusType.NotSet || a.TransmitStatus == transmitStatus)
                    {
                        foreach (TestCodeMapping m in a.Analyte.TestCodeAliasList)
                        {
                            if (string.Equals(NormalizeAnalyteCode(m.AlternateTestCode), NormalizeAnalyteCode(analyteCode), StringComparison.OrdinalIgnoreCase))
                            {
                                return a;
                            }
                        }
                    }
                }
            }

            return null;
        }

        private string NormalizeAnalyteCode(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
                return string.Empty;

            code = code.Trim().TrimStart('0');

            return string.IsNullOrEmpty(code)
                ? "0"
                : code.ToUpperInvariant();
        }

        public ReportAnalyte[] Find(string analyteCode, string orderedCode)
        {

            var analytes = new List<ReportAnalyte>();

            foreach (ReportAnalyte a in List)
            {
                if ((a.Analyte.Code.TrimStart(new char[] { '0' }).ToUpper() ?? "") == (analyteCode.TrimStart(new char[] { '0' }).ToUpper() ?? "") && a.ContainsOrderCode(orderedCode))   // 'a.OrderingAnalyteCode.TrimStart(New Char() {"0"}) = orderedCode.TrimStart(New Char() {"0"}) Then
                {
                    analytes.Add(a);
                }
                // For those that are aliases
                foreach (TestCodeMapping m in a.Analyte.TestCodeAliasList)
                {
                    if ((m.AlternateTestCode.TrimStart(new char[] { '0' }).ToUpper() ?? "") == (analyteCode.TrimStart(new char[] { '0' }).ToUpper() ?? "") && a.ContainsOrderCode(orderedCode))   // 'a.OrderingAnalyteCode.TrimStart(New Char() {"0"}) = orderedCode.TrimStart(New Char() {"0"}) Then
                    {
                        analytes.Add(a);
                    }
                }
            }

            return analytes.ToArray();

        }

        public ReportAnalyte[] Find(string analyteCode, int referenceLabId = 0)
        {

            var analytes = new List<ReportAnalyte>();

            if (referenceLabId != 0)
            {
                foreach (ReportAnalyte a in List)
                {
                    if ((a.Analyte.ReferenceLabeAnalyteCode.ToUpper() ?? "") == (analyteCode.ToUpper() ?? "") && a.Analyte.ReferenceLabId == referenceLabId)
                    {
                        analytes.Add(a);
                    }
                }
            }
            else
            {
                foreach (ReportAnalyte a in List)
                {
                    if ((a.Analyte.Code.TrimStart(new char[] { '0' }).ToUpper() ?? "") == (analyteCode.TrimStart(new char[] { '0' }).ToUpper() ?? ""))
                    {
                        analytes.Add(a);
                    }
                    // For those that are aliases
                    foreach (TestCodeMapping m in a.Analyte.TestCodeAliasList)
                    {
                        if ((m.AlternateTestCode.TrimStart(new char[] { '0' }).ToUpper() ?? "") == (analyteCode.TrimStart(new char[] { '0' }).ToUpper() ?? ""))
                        {
                            analytes.Add(a);
                        }
                    }
                }
            }
            return analytes.ToArray();
        }

        internal void Update()
        {
            m_list.Update();
            if (Configuration.LISSettings.GetBool("ReportAnalyteBatching"))
            {
                var archiveList = new ReportAnalyteList();
                foreach (ReportAnalyte a in m_list.ArchivedDeletedList)
                {
                    if (a.IsDirty)
                        archiveList.Add(a);
                }
                if (archiveList.Count > 0)
                {
                    archiveList.Update();
                }
            }

            else
            {
                foreach (ReportAnalyte a in m_list.ArchivedDeletedList)
                {
                    if (a.IsDirty)
                        a.Update();
                }
            }

        }

        internal void SetOrigResultStatus()
        {
            m_list.SetOrigResultStatus();
        }

        public override bool IsDirty
        {
            get
            {
                if (m_list.IsDirty)
                    return true;

                // Archived analytes can be updated!
                foreach (ReportAnalyte a in m_list.ArchivedDeletedList)
                {
                    if (a.IsDirty)
                        return true;
                }
                return false;
            }
        }

        public List<string> GetAuditItems()
        {
            var lst = new List<string>();

            foreach (ReportAnalyte c in m_list)
                lst.AddRange(c.GetFormattedAuditItems);

            foreach (ReportAnalyte c in m_list.ArchivedDeletedList)
                lst.AddRange(c.GetFormattedAuditItems);

            return lst;

        }

        public void ResetAudit()
        {
            foreach (ReportAnalyte c in m_list)
                c.ResetAuditItems();
        }


    }
} // OrderAnalytes