using System;
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '
// '  OrderAnalytePanelList.vb
// '  Implementation of the Class OrderAnalytePanelList
// '  Generated by Enterprise Architect
// '  Created on:      31-Jan-2008 5:17:28 PM
// '  Original author: Angelo Galeotafiore
// '  
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
// '  Modification history:
// '  
// '
// ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

using Bioreference.Data;
using Microsoft.VisualBasic.CompilerServices;

namespace Bioreference.LIS
{

    [Serializable()]
    public class ReportAnalytePanelList : DataClassCollectionBase
    {

        internal ReportAnalytePanelList()
        {
        }

        /// 
    /// <param name="panel"></param>
        internal void Add(ReportAnalytePanel panel)
        {
            List.Add(panel);
        }

        /// 
    /// <param name="index"></param>
        public ReportAnalytePanel this[int index]
        {
            get
            {
                return (ReportAnalytePanel)List[index];
            }
        }

        /// 
    /// <param name="panel"></param>
        internal void Remove(ReportAnalytePanel panel)
        {
            List.Remove(panel);
        }

        internal void Update()
        {

            foreach (ReportAnalytePanel p in List)
            {
                if (p.IsDirty)
                {
                    p.Update();
                }
            }

            if (!(DeletedItemsList == null))
            {
                foreach (ReportAnalytePanel p in DeletedItemsList)
                {
                    if (p.IsNew == false)
                    {
                        // vcc: Delete analytes part of the panel
                        // For Each a As ReportAnalyte In p.Analytes.List
                        // a.Delete()
                        // Next
                        p.Delete();
                    }

                }
                DeletedItemsList.Clear();
            }

        }

        /// <summary>
    /// Quick fix for audit display, should be built from base class.
    /// Allow loading of deleted list so that we can get audit info.
    /// </summary>
    /// <param name="panel"></param>
    /// <remarks></remarks>
        internal void AddToArchiveDeletedList(ReportAnalytePanel panel)
        {

            ArchivedDeletedList.Add(panel);

        }


        // Public ReadOnly Property DeletedPanels() As ReportAnalytePanel()
        // Get
        // Dim list As List(Of ReportAnalytePanel) = New List(Of ReportAnalytePanel)
        // If Not IsNothing(Me.ArchivedDeletedList) Then
        // For Each o As Object In Me.DeletedItemsList
        // list.Add(o)
        // Next
        // End If
        // Return list.ToArray()
        // End Get
        // End Property

        public bool UnDeletePanel(long panelId)
        {

            foreach (ReportAnalytePanel p in ArchivedDeletedList)
            {
                if (p.Id == panelId)
                {
                    return UnDeletePanel(p);
                }
            }

            return default;

        }

        internal bool UnDeletePanel(ReportAnalytePanel panel)
        {

            // Check to see that the panel doesn't already exist in active list
            foreach (ReportAnalytePanel p in List)
            {
                // If p.Id = panel.Id Then Return False
                if ((p.PanelCode ?? "") == (panel.PanelCode ?? ""))
                    return false;
            }

            // Me.DeletedItemsList.Remove(panel)
            panel.FlagUnDeleted();
            List.Add(panel);

            // 'vcc: remove analytes which are part of the panel
            // For Each a As ReportAnalyte In panel.Analytes.List.ArchivedDeletedList
            // a.FlagUnDeleted()
            // panel.Analytes.List.UnDeleteAnalyte(a.ID)
            // Next


            // Me.DeletedItemsList.Remove(panel)
            return true;

        }

        public ReportAnalytePanel FindDeleted(object panelCode)
        {
            foreach (object o in ArchivedDeletedList)
            {
                if (Conversions.ToBoolean(Operators.ConditionalCompareObjectEqual(((ReportAnalytePanel)o).PanelCode, panelCode, false)))
                    return (ReportAnalytePanel)o;
            }
            return null;
        }

    }
} // OrderAnalytePanelList